var _yt_www={};(function(g){var window=this;var baa,caa,ra,Ba,ab,kaa,bb,cb,db,eb,jb,laa,kb,maa,naa,rb,Cb,Rb,oc,taa,uaa,saa,Sc,Tc,Zc,ad,xaa,fd,jd,dd,bd,zaa,id,gd,hd,ld,yaa,qd,Aaa,Baa,Ld,Daa,Vd,be,ae,Faa,Gaa,ce,de,fe,Iaa,je,pe,oe,ke,te,Naa,xe,ue,ve,Maa,Ae,ze,Ce,ne,he,ge,ie,De,re,Be,se,Fe,Paa,Laa,Me,Pe,Se,Ue,$e,af,qf,rf,sf,vf,xf,yf,zf,Cf,Bf,Ef,Af,Ff,tf,wf,$aa,Gf,Hf,aba,bba,Nf,Pf,Rf,dba,Yf,Zf,bg,$f,eba,ig,pg,og,fba,sg,lba,kba,jba,yg,iba,gba,hba,mba,Fg,nba,Gg,Ig,oba,pba,Jg,Kg,Pg,Tg,Ug,Vg,Yg,Zg,$g,vba,wba,Qg,Sg,Og,uba,Rg,yba,gh,zba,Aba,hh,ih,pa,
aaa;g.ca=function(a){return function(){return g.ba[a].apply(this,arguments)}};
g.da=function(a){return void 0!==a};
g.m=function(a,b,c){a=a.split(".");c=c||g.ea;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&g.da(b)?c[d]=b:c[d]?c=c[d]:c=c[d]={}};
g.p=function(a,b){for(var c=a.split("."),d=b||g.ea,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d};
g.fa=function(){};
g.ga=function(a){a.getInstance=function(){return a.uc?a.uc:a.uc=new a}};
g.ha=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};
g.ia=function(a){return"array"==g.ha(a)};
g.ja=function(a){var b=g.ha(a);return"array"==b||"object"==b&&"number"==typeof a.length};
g.ka=function(a){return"string"==typeof a};
g.ma=function(a){return"number"==typeof a};
g.na=function(a){return"function"==g.ha(a)};
g.oa=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};
g.qa=function(a){return a[pa]||(a[pa]=++aaa)};
baa=function(a,b,c){return a.call.apply(a.bind,arguments)};
caa=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};
g.q=function(a,b,c){g.q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?baa:caa;return g.q.apply(null,arguments)};
g.r=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};
g.t=function(a,b){function c(){}
c.prototype=b.prototype;a.L=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.WU=function(a,c,h){for(var k=Array(arguments.length-2),l=2;l<arguments.length;l++)k[l-2]=arguments[l];return b.prototype[c].apply(a,k)}};
ra=function(a){ra[" "](a);return a};
g.sa=function(a,b){try{return ra(a[b]),!0}catch(c){}return!1};
g.ta=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,g.ta);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};
g.ua=function(a,b){return 0==a.lastIndexOf(b,0)};
g.va=function(a){return/^[\s\xa0]*$/.test(a)};
g.wa=function(a){return(0,window.encodeURIComponent)(String(a))};
g.xa=function(a){if(!daa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(eaa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(faa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(gaa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(haa,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(iaa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(jaa,"&#0;"));return a};
g.ya=function(a,b){return-1!=a.indexOf(b)};
g.za=function(a){return null==a?"":String(a)};
g.Ca=function(a,b){for(var c=0,d=(0,g.Aa)(String(a)).split("."),e=(0,g.Aa)(String(b)).split("."),h=Math.max(d.length,e.length),k=0;0==c&&k<h;k++){var l=d[k]||"",n=e[k]||"",u=RegExp("(\\d*)(\\D*)","g"),w=RegExp("(\\d*)(\\D*)","g");do{var I=u.exec(l)||["","",""],U=w.exec(n)||["","",""];if(0==I[0].length&&0==U[0].length)break;c=Ba(0==I[1].length?0:(0,window.parseInt)(I[1],10),0==U[1].length?0:(0,window.parseInt)(U[1],10))||Ba(0==I[2].length,0==U[2].length)||Ba(I[2],U[2])}while(0==c)}return c};
Ba=function(a,b){return a<b?-1:a>b?1:0};
g.Da=function(a){for(var b=0,c=0;c<a.length;++c)b=31*b+a.charCodeAt(c)>>>0;return b};
g.Ga=function(a,b,c){b=g.Fa(a,b,c);return 0>b?null:g.ka(a)?a.charAt(b):a[b]};
g.Fa=function(a,b,c){for(var d=a.length,e=g.ka(a)?a.split(""):a,h=0;h<d;h++)if(h in e&&b.call(c,e[h],h,a))return h;return-1};
g.Ia=function(a,b){return 0<=(0,g.Ha)(a,b)};
g.Ka=function(a,b){var c=(0,g.Ha)(a,b),d;(d=0<=c)&&g.Ja(a,c);return d};
g.Ja=function(a,b){return 1==Array.prototype.splice.call(a,b,1).length};
g.La=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
g.Ma=function(a){return function(){return a}};
g.Oa=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};
g.Pa=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};
g.Qa=function(a,b,c){for(var d in a)if(b.call(c,a[d],d,a))return d};
g.Ra=function(a){for(var b in a)return!1;return!0};
g.Sa=function(a,b){b in a&&delete a[b]};
g.Ta=function(a,b,c){if(null!==a&&b in a)throw Error('The object already contains the key "'+b+'"');a[b]=c};
g.Ua=function(a){var b={},c;for(c in a)b[c]=a[c];return b};
g.Wa=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var h=0;h<Va.length;h++)c=Va[h],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
g.Ya=function(a){return g.ya(g.Xa,a)};
g.Za=function(){return g.Ya("Trident")||g.Ya("MSIE")};
g.$a=function(){return(g.Ya("Chrome")||g.Ya("CriOS"))&&!g.Ya("Edge")};
ab=function(a){g.ea.setTimeout(function(){throw a;},0)};
kaa=function(){var a=g.ea.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!g.Ya("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,g.q)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);
b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});
if("undefined"!==typeof a&&!g.Za()){var b=new a,c={},d=c;b.port1.onmessage=function(){if(g.da(c.next)){c=c.next;var a=c.Hp;c.Hp=null;a()}};
return function(a){d.next={Hp:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b=window.document.createElement("SCRIPT");
b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};
window.document.documentElement.appendChild(b)}:function(a){g.ea.setTimeout(a,0)}};
bb=function(a,b,c){this.F=c;this.B=a;this.D=b;this.C=0;this.A=null};
cb=function(a,b){a.D(b);a.C<a.F&&(a.C++,b.next=a.A,a.A=b)};
db=function(){this.C=this.A=null};
eb=function(){this.next=this.scope=this.pe=null};
jb=function(a,b){fb||laa();gb||(fb(),gb=!0);var c=hb,d=ib.get();d.set(a,b);c.C?c.C.next=d:c.A=d;c.C=d};
laa=function(){if(g.ea.Promise&&g.ea.Promise.resolve){var a=g.ea.Promise.resolve(void 0);fb=function(){a.then(kb)}}else fb=function(){var a=kb;
!g.na(g.ea.setImmediate)||g.ea.Window&&g.ea.Window.prototype&&!g.Ya("Edge")&&g.ea.Window.prototype.setImmediate==g.ea.setImmediate?(lb||(lb=kaa()),lb(a)):g.ea.setImmediate(a)}};
kb=function(){for(var a;a=hb.remove();){try{a.pe.call(a.scope)}catch(b){ab(b)}cb(ib,a)}gb=!1};
g.mb=function(){this.Md=this.Md;this.Jb=this.Jb};
g.pb=function(a,b){g.nb(a,g.r(g.ob,b))};
g.nb=function(a,b){a.Md?g.da(void 0)?b.call(void 0):b():(a.Jb||(a.Jb=[]),a.Jb.push(g.da(void 0)?(0,g.q)(b,void 0):b))};
g.ob=function(a){a&&"function"==typeof a.dispose&&a.dispose()};
g.qb=function(a){g.mb.call(this);this.D=1;this.C=[];this.B=0;this.A=[];this.rd={};this.F=!!a};
maa=function(a,b,c){jb(function(){a.apply(b,c)})};
g.tb=function(a){rb(g.sb,arguments)};
g.v=function(a,b){return a in g.sb?g.sb[a]:b};
g.vb=function(a,b){g.na(a)&&(a=g.ub(a));return window.setTimeout(a,b)};
g.wb=function(a,b){g.na(a)&&(a=g.ub(a));return window.setInterval(a,b)};
g.xb=function(a){window.clearTimeout(a)};
g.yb=function(a){window.clearInterval(a)};
g.ub=function(a){return a&&window.yterr?function(){try{return a.apply(this,arguments)}catch(b){throw g.zb(b),b;}}:a};
g.zb=function(a,b,c,d,e){var h=g.p("yt.logging.errors.log");h?h(a,b,c,d,e):(h=g.v("ERRORS",[]),h.push([a,b,c,d,e]),g.tb("ERRORS",h))};
naa=function(a,b,c,d,e){var h=!1;if(g.sb.So&&g.sb.So.log_window_onerror_fraction&&Math.random()<g.sb.So.log_window_onerror_fraction)h=!0;else for(var k=window.document.getElementsByTagName("script"),l=0,n=k.length;l<n;l++)if(0<k[l].src.indexOf("/debug-")){h=!0;break}h&&(e||(e=Error(),e.message=a,e.fileName=b,e.lineNumber=c,(0,window.isNaN)(d)||(e.columnNumber=d)),g.zb(e))};
g.Bb=function(a){return a in g.Ab};
rb=function(a,b){if(1<b.length){var c=b[0];a[c]=b[1]}else{var d=b[0];for(c in d)a[c]=d[c]}};
g.x=function(a,b,c){var d=Cb();if(d){var e=d.subscribe(a,function(){if(!Db||Db!=e){var d=arguments,k;k=function(){Eb[e]&&b.apply(c||window,d)};
try{Fb[a]?k():g.vb(k,0)}catch(l){g.zb(l)}}},c);
Eb[e]=!0;Gb[a]||(Gb[a]=[]);Gb[a].push(e);return e}return 0};
g.Hb=function(a){var b=Cb();b&&("number"==typeof a?a=[a]:"string"==typeof a&&(a=[(0,window.parseInt)(a,10)]),(0,g.y)(a,function(a){b.unsubscribeByKey(a);delete Eb[a]}))};
g.z=function(a,b){var c=Cb();return c?c.publish.apply(c,arguments):!1};
g.Ib=function(a,b){Fb[a]=!0;var c=Cb(),c=c?c.publish.apply(c,arguments):!1;Fb[a]=!1;return c};
Cb=function(){return g.p("yt.pubsub.instance_")};
g.Jb=function(){return!!g.p("yt.scheduler.instance")};
g.Kb=function(a,b){(0,window.isNaN)(b)&&(b=void 0);var c=g.p("yt.scheduler.instance.addJob");return c?c(a,1,b):void 0===b?(a(),window.NaN):g.vb(a,b||0)};
g.Lb=function(a,b){return g.Kb(a,b)};
g.Mb=function(a){if(!(0,window.isNaN)(a)){var b=g.p("yt.scheduler.instance.cancelJob");b?b(a):g.xb(a)}};
g.Nb=function(a){for(var b=0,c=a.length;b<c;b++)g.Mb(a[b])};
g.Ob=function(a,b,c,d,e){this.name=a;this.deps=b||[];this.page=c||"";this.H=d?g.ub(d):null;this.F=e?g.ub(e):null;this.D=[];this.A=this.C=0};
g.Pb=function(a){g.Mb(a.C);a.C=g.Lb((0,g.q)(a.init,a))};
g.Tb=function(a){a.name in Qb&&Rb(a.name);Qb[a.name]={reqs:[],disable:(0,g.q)(a.disable,a)};(0,g.y)(a.deps,function(b){if(!(b in Qb))throw Error("Module "+b+" required by "+a.name);Qb[b].reqs.push(a.name)});
a.enable()};
Rb=function(a){if(a in Qb){var b=Qb[a];(0,g.y)(b.reqs,function(a){Rb(a)});
try{b.disable()}catch(c){}delete Qb[a]}};
g.Vb=function(){this.A="";this.C=g.Ub};
g.Wb=function(a){var b=new g.Vb;b.A=a;return b};
g.Yb=function(){this.A="";this.C=Xb};
g.$b=function(a){if(a instanceof g.Yb&&a.constructor===g.Yb&&a.C===Xb)return a.A;g.ha(a);return"type_error:SafeUrl"};
g.bc=function(a){if(a instanceof g.Yb)return a;a=a.Tf?a.Qe():String(a);oaa.test(a)||(a="about:invalid#zClosurez");return g.ac(a)};
g.ac=function(a){var b=new g.Yb;b.A=a;return b};
g.dc=function(){this.A="";this.B=g.cc;this.C=null};
g.ec=function(a,b){var c=new g.dc;c.A=a;c.C=b;return c};
g.fc=function(a,b){var c;c=b instanceof g.Yb?b:g.bc(b);a.href=g.$b(c)};
g.A=function(a,b){return a?a.dataset?a.dataset[g.gc(b)]:a.getAttribute("data-"+b):null};
g.gc=function(a){return hc[a]||(hc[a]=String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()}))};
g.jc=function(a,b){var c=g.ic(a);window.spf.script.load(a,c,b)};
g.ic=function(a){var b="";if(a){var c=a.indexOf("jsbin/"),d=a.lastIndexOf(".js"),e=c+6;-1<c&&-1<d&&d>e&&(b=a.substring(e,d),b=b.replace(paa,""),b=b.replace(qaa,""),b=b.replace("debug-",""),b=b.replace("tracing-",""))}return b};
g.kc=function(a){if(a.classList)return a.classList;a=a.className;return g.ka(a)&&a.match(/\S+/g)||[]};
g.B=function(a,b){return a.classList?a.classList.contains(b):g.Ia(g.kc(a),b)};
g.lc=function(a,b){this.x=g.da(a)?a:0;this.y=g.da(b)?b:0};
g.mc=function(a,b){this.width=a;this.height=b};
g.nc=function(){return g.Ya("iPhone")&&!g.Ya("iPod")&&!g.Ya("iPad")};
oc=function(){var a=g.ea.document;return a?a.documentMode:void 0};
g.rc=function(a){return pc[a]||(pc[a]=0<=g.Ca(g.qc,a))};
g.tc=function(a){return Number(g.sc)>=a};
g.C=function(a){return g.ka(a)?window.document.getElementById(a):a};
g.uc=function(a){return g.ka(a)?window.document.getElementById(a):a};
g.wc=function(a,b){g.Oa(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:vc.hasOwnProperty(d)?a.setAttribute(vc[d],b):g.ua(d,"aria-")||g.ua(d,"data-")?a.setAttribute(d,b):a[d]=b})};
g.yc=function(a){return g.xc(a||window)};
g.xc=function(a){a=a.document;a=g.zc(a)?a.documentElement:a.body;return new g.mc(a.clientWidth,a.clientHeight)};
g.Bc=function(a){var b=g.Ac(a);a=a.parentWindow||a.defaultView;return g.D&&g.rc("10")&&a.pageYOffset!=b.scrollTop?new g.lc(b.scrollLeft,b.scrollTop):new g.lc(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};
g.Ac=function(a){return a.scrollingElement?a.scrollingElement:!g.Cc&&g.zc(a)?a.documentElement:a.body||a.documentElement};
g.Ec=function(a,b,c){return g.Dc(window.document,arguments)};
g.Dc=function(a,b){var c=String(b[0]),d=b[1];if(!raa&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',g.xa(d.name),'"');if(d.type){c.push(' type="',g.xa(d.type),'"');var e={};g.Wa(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&(g.ka(d)?c.className=d:g.ia(d)?c.className=d.join(" "):g.wc(c,d));2<b.length&&g.Fc(a,c,b,2);return c};
g.Fc=function(a,b,c,d){function e(c){c&&b.appendChild(g.ka(c)?a.createTextNode(c):c)}
for(;d<c.length;d++){var h=c[d];!g.ja(h)||g.oa(h)&&0<h.nodeType?e(h):(0,g.y)(saa(h)?g.La(h):h,e)}};
g.zc=function(a){return"CSS1Compat"==a.compatMode};
g.Gc=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};
g.Hc=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};
g.Ic=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};
taa=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};
uaa=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};
g.Jc=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};
saa=function(a){if(a&&"number"==typeof a.length){if(g.oa(a))return"function"==typeof a.item||"string"==typeof a.item;if(g.na(a))return"function"==typeof a.item}return!1};
g.Kc=function(a,b,c,d){c||(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null};
g.Mc=function(a){var b=a.__yt_uid_key;b||(b=Lc(),a.__yt_uid_key=b);return b};
g.Nc=function(a){var b=a.cloneNode(!1);"TR"==b.tagName||"SELECT"==b.tagName?(0,g.y)(a.childNodes,function(a){b.appendChild(g.Nc(a))}):b.innerHTML=a.innerHTML;
return b};
g.Oc=function(){var a=window.document;if("visibilityState"in a)return a.visibilityState;var b=vaa+"VisibilityState";if(b in a)return a[b]};
g.Pc=function(a){return g.v("EXPERIMENT_FLAGS",{})[a]};
g.Rc=function(a,b){return(new g.Qc(b)).Sb(a)};
g.Qc=function(a){this.A=a};
Sc=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(g.ia(b)){var d=b;b=d.length;c.push("[");for(var e="",h=0;h<b;h++)c.push(e),e=d[h],Sc(a,a.A?a.A.call(d,String(h),e):e,c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");h="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(e=b[d],"function"!=typeof e&&(c.push(h),Tc(d,c),c.push(":"),Sc(a,a.A?a.A.call(b,d,e):e,c),h=","));c.push("}");return}}switch(typeof b){case "string":Tc(b,
c);break;case "number":c.push((0,window.isFinite)(b)&&!(0,window.isNaN)(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("Unknown type: "+typeof b);}}};
Tc=function(a,b){b.push('"',a.replace(waa,function(a){var b=Uc[a];b||(b="\\u"+(a.charCodeAt(0)|65536).toString(16).substr(1),Uc[a]=b);return b}),'"')};
g.Vc=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0};
g.Wc=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};
g.Yc=function(a,b){this.A=0;this.K=void 0;this.D=this.C=this.B=null;this.F=this.H=!1;if(a!=g.fa)try{var c=this;a.call(b,function(a){g.Xc(c,2,a)},function(a){g.Xc(c,3,a)})}catch(d){g.Xc(this,3,d)}};
Zc=function(){this.next=this.context=this.C=this.B=this.A=null;this.D=!1};
ad=function(a,b,c){var d=$c.get();d.B=a;d.C=b;d.context=c;return d};
xaa=function(a,b,c){bd(a,b,c,null)||jb(g.r(b,a))};
g.cd=function(a){return new g.Yc(function(b,c){var d=a.length,e=[];if(d)for(var h=function(a,c){d--;e[a]=c;0==d&&b(e)},k=function(a){c(a)},l=0,n;l<a.length;l++)n=a[l],xaa(n,g.r(h,l),k);
else b(e)})};
g.ed=function(a,b){dd(a,null,b,void 0)};
fd=function(a,b){if(0==a.A)if(a.B){var c=a.B;if(c.C){for(var d=0,e=null,h=null,k=c.C;k&&(k.D||(d++,k.A==a&&(e=k),!(e&&1<d)));k=k.next)e||(h=k);e&&(0==c.A&&1==d?fd(c,b):(h?(d=h,d.next==c.D&&(c.D=d),d.next=d.next.next):gd(c),hd(c,e,3,b)))}a.B=null}else g.Xc(a,3,b)};
jd=function(a,b){a.C||2!=a.A&&3!=a.A||id(a);a.D?a.D.next=b:a.C=b;a.D=b};
dd=function(a,b,c,d){var e=ad(null,null,null);e.A=new g.Yc(function(a,k){e.B=b?function(c){try{var e=b.call(d,c);a(e)}catch(u){k(u)}}:a;
e.C=c?function(b){try{var e=c.call(d,b);!g.da(e)&&b instanceof g.kd?k(b):a(e)}catch(u){k(u)}}:k});
e.A.B=a;jd(a,e);return e.A};
g.Xc=function(a,b,c){0==a.A&&(a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself")),a.A=1,bd(c,a.R,a.Y,a)||(a.K=c,a.A=b,a.B=null,id(a),3!=b||c instanceof g.kd||yaa(a,c)))};
bd=function(a,b,c,d){if(a instanceof g.Yc)return jd(a,ad(b||g.fa,c||null,d)),!0;if(g.Wc(a))return a.then(b,c,d),!0;if(g.oa(a))try{var e=a.then;if(g.na(e))return zaa(a,e,b,c,d),!0}catch(h){return c.call(d,h),!0}return!1};
zaa=function(a,b,c,d,e){function h(a){l||(l=!0,d.call(e,a))}
function k(a){l||(l=!0,c.call(e,a))}
var l=!1;try{b.call(a,k,h)}catch(n){h(n)}};
id=function(a){a.H||(a.H=!0,jb(a.G,a))};
gd=function(a){var b=null;a.C&&(b=a.C,a.C=b.next,b.next=null);a.C||(a.D=null);return b};
hd=function(a,b,c,d){if(3==c&&b.C&&!b.D)for(;a&&a.F;a=a.B)a.F=!1;if(b.A)b.A.B=null,ld(b,c,d);else try{b.D?b.B.call(b.context):ld(b,c,d)}catch(e){md.call(null,e)}cb($c,b)};
ld=function(a,b,c){2==b?a.B.call(a.context,c):a.C&&a.C.call(a.context,c)};
yaa=function(a,b){a.F=!0;jb(function(){a.F&&md.call(null,b)})};
g.kd=function(a){g.ta.call(this,a)};
g.nd=function(){return{apiaryHost:g.v("APIARY_HOST",void 0),sp:g.v("APIARY_HOST_FIRSTPARTY",void 0),gapiHintOverride:g.v("GAPI_HINT_OVERRIDE"),gapiHintParams:g.v("GAPI_HINT_PARAMS",void 0),innertubeApiKey:g.v("INNERTUBE_API_KEY",void 0),innertubeApiVersion:g.v("INNERTUBE_API_VERSION",void 0),OD:g.v("INNERTUBE_CONTEXT_CLIENT_NAME","WEB"),innertubeContextClientVersion:g.v("INNERTUBE_CONTEXT_CLIENT_VERSION",void 0),QD:g.v("INNERTUBE_CONTEXT_HL",void 0),PD:g.v("INNERTUBE_CONTEXT_GL",void 0),BV:g.v("XHR_APIARY_HOST",
void 0)}};
g.od=function(a){a={client:{hl:a.QD,gl:a.PD,clientName:a.OD,clientVersion:a.innertubeContextClientVersion}};g.v("DELEGATED_SESSION_ID")&&(a.user={onBehalfOfUser:g.v("DELEGATED_SESSION_ID")});return a};
qd=function(){this.A=g.nd();pd||(pd=Aaa(this.A))};
Aaa=function(a){return(new g.Yc(function(b){g.jc(g.v("GAPI_LOADER_URL",void 0),function(){try{g.p("yt.gapi.load")("client",{gapiHintOverride:a.gapiHintOverride,_c:{jsl:{h:a.gapiHintParams}},callback:b})}catch(c){g.zb(c)}})})).then(function(){})};
Baa=function(a,b,c,d){var e={path:"/youtubei/"+a.A.innertubeApiVersion+"/"+b,headers:{"X-Goog-Visitor-Id":g.v("VISITOR_DATA")},method:"POST",body:g.Rc(c)},h=(0,g.q)(a.D,a);pd.then(function(){h();g.p("gapi.client.request")(e).execute(d||g.fa)})};
g.rd=function(a,b,c){this.A=a;this.B=b;this.C=c};
g.wd=function(a,b){g.sd[a.endpoint]=g.sd[a.endpoint]||[];var c=g.sd[a.endpoint];c.push(a.Ab);td[a.endpoint]=b;20<=c.length?g.ud():g.vd()};
g.ud=function(){g.xb(g.xd);if(!g.Ra(g.sd)){for(var a in g.sd){var b=g.yd[a];if(!b){b=td[a];if(!b)continue;b=new b;g.yd[a]=b}var c=b.C();c.requestTimeMs=Math.round((0,g.zd)());c[Caa[a]]=g.sd[a];b.B(a,c,{});delete g.sd[a]}g.Ra(g.sd)||g.vd()}};
g.vd=function(){g.xb(g.xd);g.xd=g.vb(g.ud,g.v("VISIBILITY_TIMEOUT",1E4))};
g.Ad=function(a,b,c,d){var e={};e.eventTimeMs=Math.round(d||(0,g.zd)());e[a]=b;g.wd({endpoint:"log_event",Ab:e},c)};
g.Bd=function(){var a=g.v("client-screen-nonce",void 0);a||(a=g.v("EVENT_ID",void 0));return a};
g.Cd=function(a,b,c,d,e,h,k){var l="";a&&(l+=a+":");c&&(l+="//",b&&(l+=b+"@"),l+=c,d&&(l+=":"+d));e&&(l+=e);h&&(l+="?"+h);k&&(l+="#"+k);return l};
g.Dd=function(a){return a?(0,window.decodeURI)(a):a};
g.Fd=function(a,b){return b.match(g.Ed)[a]||null};
g.Gd=function(a){return g.Dd(g.Fd(3,a))};
g.Hd=function(a){a=a.match(g.Ed);return g.Cd(null,null,null,null,a[5],a[6],a[7])};
g.Id=function(a){var b=a.indexOf("#");return 0>b?a:a.substr(0,b)};
g.Jd=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=void 0)}return a.join("")};
g.Kd=function(a,b,c){if(g.ia(b))for(var d=0;d<b.length;d++)g.Kd(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",g.wa(b))};
Ld=function(a,b){for(var c in b)g.Kd(c,b[c],a);return a};
g.Md=function(a){a=Ld([],a);a[0]="";return a.join("")};
g.Nd=function(a,b){return g.Jd(Ld([a],b))};
g.Od=function(a,b,c){a&&(c&&(c=g.Xa,c=!(c&&0<=c.toLowerCase().indexOf("cobalt"))),c?a&&(a=g.Ec("IFRAME",{src:'javascript:"data:text/html,<body><img src=\\"'+a+'\\"></body>"',style:"display:none"}),g.Jc(a).body.appendChild(a)):Daa(a,b))};
g.Pd=function(a){try{window.navigator&&window.navigator.sendBeacon&&window.navigator.sendBeacon(a,"")||g.Od(a,void 0)}catch(b){g.Od(a,void 0)}};
Daa=function(a,b){var c=new window.Image,d=""+Eaa++;Qd[d]=c;c.onload=c.onerror=function(){b&&Qd[d]&&b();delete Qd[d]};
c.src=a};
g.Rd=function(a,b){this.version=a;this.args=b};
g.Sd=function(a,b){this.topic=a;this.zf=b};
g.Ud=function(a,b){var c=g.Td();return c?c.publish.call(c,a.toString(),a,b):!1};
g.Td=function(){return g.p("yt.pubsub2.instance_")};
Vd=function(a){g.Rd.call(this,1,arguments)};
g.Wd=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d};
g.Xd=function(a,b){return a&&b?b instanceof g.Wd?b.left>=a.left&&b.right<=a.right&&b.top>=a.top&&b.bottom<=a.bottom:b.x>=a.left&&b.x<=a.right&&b.y>=a.top&&b.y<=a.bottom:!1};
g.Yd=function(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d};
g.Zd=function(a,b){var c=Math.max(a.left,b.left),d=Math.min(a.left+a.width,b.left+b.width);if(c<=d){var e=Math.max(a.top,b.top),h=Math.min(a.top+a.height,b.top+b.height);if(e<=h)return a.left=c,a.top=e,a.width=d-c,a.height=h-e,!0}return!1};
g.$d=function(a){return new g.mc(a.width,a.height)};
be=function(a){this.A=a||window;this.R=this.B=0;if(this.A.performance&&this.A.performance.timing&&this.A.performance.getEntriesByType){a=g.yc(this.A);this.G=new g.Yd(0,0,a.width,a.height);a=[];for(var b=this.A.document.getElementsByTagName("*"),c=0,d=b.length;c<d;c++){var e=b[c];if("IMG"==e.tagName||"IFRAME"==e.tagName){var h=ae(this,e,e.src);if(h){if("IFRAME"==e.tagName){var k;try{k=(new be(e.contentWindow)).B}catch(l){k=0}0<k&&(h.timing=k)}a.push(h)}}(h=this.A.getComputedStyle(e)["background-image"])&&
(h=be.A.exec(h))&&1<h.length&&(h=ae(this,e,h[1]))&&a.push(h)}this.C=a;this.F=this.A.performance.getEntriesByType("resource");this.K=this.A.performance.getEntriesByType("mark");k={};a=0;for(b=this.F.length;a<b;a++)c=this.F[a],k[c.name]=c.responseEnd;a=0;for(b=this.K.length;a<b;a++)c=this.K[a],"mark_iframe_loaded: "==c.name.slice(0,20)&&(k[c.name.slice(20)]=c.startTime);a=0;for(b=this.C.length;a<b;a++)c=this.C[a],c.timing||(c.timing=k[c.url]||0);this.H=Faa(this);this.D=Gaa(this);e=k=0;if(this.D.length)for(b=
a=0,c=this.D.length;b<c;b++)d=this.D[b],e=d.timing-e,0<e&&1>a&&(k+=(1-a)*e),e=d.timing,a=d.progress;this.B=Math.round(k||this.H);this.R=e}};
ae=function(a,b,c){return c&&b.getBoundingClientRect&&(b=b.getBoundingClientRect(),b=new g.Yd(b.left,b.top,b.width,b.height),g.Zd(b,a.G))?new ce(b,c):null};
Faa=function(a){var b,c=a.A,d=c.performance.timing.navigationStart;if("msFirstPaint"in c.performance.timing)b=c.performance.timing.A-d;else if("chrome"in c&&"loadTimes"in c.chrome){var e=c.chrome.loadTimes(),h=e.firstPaintTime;if(0<h){var k=e.startLoadTime;"requestTime"in e&&(k=e.requestTime);h>=k&&(b=1E3*(h-k))}}if(void 0===b||0>b||12E4<b){b=c.performance.timing.responseStart-d;for(var l={},c=c.document.getElementsByTagName("head")[0].children,d=0,e=c.length;d<e;d++)h=c[d],"SCRIPT"==h.tagName&&h.src&&
!h.async?l[h.src]=!0:"LINK"==h.tagName&&"stylesheet"==h.rel&&h.href&&(l[h.href]=!0);a.F.some(function(a){if(!l[a.name]||"script"!=a.initiatorType&&"link"!=a.initiatorType)return!0;a=a.responseEnd;if(void 0===b||a>b)b=a})}return Math.max(b,0)||0};
Gaa=function(a){for(var b={0:0},c=0,d=a.H,e=0,h=a.C.length;e<h;e++){var k=a.C[e],l=d;k.timing>d&&(l=k.timing);b[l]||(b[l]=0);k=g.$d(k.region).og();b[l]+=k;c+=k}e=g.$d(a.G).og();0<e&&(e=.1*Math.max(e-c,0),d in b||(b[d]=0),b[d]+=e,c+=e);d=[];if(c){for(var n in b)a=new de((0,window.parseFloat)(n),b[n]),d.push(a);d.sort(function(a,b){return a.timing-b.timing});
e=b=0;for(h=d.length;e<h;e++)a=d[e],b+=a.og,a.progress=b/c}return d};
ce=function(a,b){this.region=a;this.url=b};
de=function(a,b){this.og=b;this.timing=a};
fe=function(a){ee.mark&&(Haa.test(a)||(a="mark_"+a),ee.mark(a))};
Iaa=function(){if("cold"==ge().yt_lt){var a=he(),b=ie(),c;for(c in a)g.ua(c,"_")||"tick_"+c in b||je(c,a[c]);a=ge();for(c in a)"info_"+c in b||ke(c,a[c])}};
g.me=function(a,b,c){b||"_"==a[0]||fe(a);var d=he(c),e=b||(0,g.zd)();d[a]&&(d["_"+a]=d["_"+a]||[d[a]],d["_"+a].push(e));d[a]=e;je(a,b,c)||g.le(!1,c);return d[a]};
je=function(a,b,c){ie(c)["tick_"+a]=b;return g.Pc("csi_on_gel")?(c=ne(c),"_start"==a?g.Ad("latencyActionBaselined",{clientActionNonce:c},qd,b):g.Ad("latencyActionTicked",{tickName:a,clientActionNonce:c},qd,b),!0):!1};
pe=function(a,b){oe("yt_sts",a,void 0);g.me("_start",b,void 0)};
oe=function(a,b,c){ge(c)[a]=b;ke(a,b,c)};
ke=function(a,b,c){ie(c)["info_"+a]=b;if(g.Pc("csi_on_gel"))if(a in qe){var d={};a=qe[a];g.Ia(Jaa,a)&&(b=!!b);d[a]=b;b=ne(c);d.clientActionNonce=b;g.Ad("latencyActionInfo",d,qd)}else g.zb(Error("Unknown label "+a+" logged with GEL CSI."))};
te=function(a){re(a);Kaa();se(!1,a)};
Naa=function(){var a=g.v("TIMING_INFO",{}),b;for(b in a)oe(b,a[b]);(a=g.Bd())&&oe("csn",a);(a=g.v("PREVIOUS_ACTION",void 0))&&oe("pa",a);a=ge();a.p=g.v("CLIENT_PROTOCOL")||"unknown";a.t=g.v("CLIENT_TRANSPORT")||"unknown";ee.now&&ee.timing?(a=ee.timing.navigationStart+ee.now(),a=Math.round((0,g.E)()-a)):a=null;null!=a&&oe("yt_hrd",a);window.navigator&&window.navigator.sendBeacon&&oe("ba",1);oe("yt_vis",Laa());if("cold"==ge().yt_lt){a=ee.timing||{};g.Pc("cold_load_nav_start_web")&&a.navigationStart&&
(pe("n",a.navigationStart),g.me("srt",a.responseStart));a:if(a.msFirstPaint)b=Math.max(0,a.msFirstPaint);else{if(b=window.chrome)if(b=b.loadTimes,g.na(b)){b=b();var c=1E3*Math.min(b.requestTime||window.Infinity,b.startLoadTime||window.Infinity),c=window.Infinity===c?0:a.navigationStart-c;b=Math.max(0,Math.round(1E3*b.firstPaintTime+c)||0);break a}b=0}0<b&&g.me("fpt",b);ue(a);ee.getEntriesByType&&Maa();a=g.v("SPEEDINDEX_FOR_ACTIONS",void 0);b=g.v("TIMING_ACTION",void 0);a&&-1<a.indexOf(b)&&(a=(0,g.zd)(),
b=new be,c=(0,g.zd)(),0<b.B&&(oe("si",b.B),g.me("vsc",ve(b.R)),g.me("sics",a),g.me("sice",c)));a=[];if(window.document.querySelector&&ee&&ee.getEntriesByName)for(var d in we)if(b=window.document.querySelector(d)){var c="",e=b.nodeName;"SCRIPT"==e?c=b.src:"LINK"==e&&(c=b.href);c&&(b=ee.getEntriesByName(c))&&b[0]&&a.push(we[d]+"."+Math.round(b[0].duration))}a.length&&oe("rs",a.join(","))}};
xe=function(a){var b=he(a);if(b.aft)return b.aft;a=g.v((a||"")+"TIMING_AFT_KEYS",["ol"]);for(var c=a.length,d=0;d<c;d++){var e=b[a[d]];if(e)return e}return window.NaN};
ue=function(a){g.me("nreqs",a.requestStart,void 0);g.me("nress",a.responseStart,void 0);g.me("nrese",a.responseEnd,void 0);0<a.redirectEnd-a.redirectStart&&(g.me("nrs",a.redirectStart,void 0),g.me("nre",a.redirectEnd,void 0));0<a.domainLookupEnd-a.domainLookupStart&&(g.me("ndnss",a.domainLookupStart,void 0),g.me("ndnse",a.domainLookupEnd,void 0));0<a.connectEnd-a.connectStart&&(g.me("ntcps",a.connectStart,void 0),g.me("ntcpe",a.connectEnd,void 0));a.secureConnectionStart>=a.navigationStart&&0<a.connectEnd-
a.secureConnectionStart&&(g.me("nstcps",a.secureConnectionStart,void 0),g.me("ntcpe",a.connectEnd,void 0))};
ve=function(a){return Math.round(ee.timing.navigationStart+a)};
Maa=function(){var a=window.location.protocol,b=ee.getEntriesByType("resource"),c=b.filter(function(b){return 0==b.name.indexOf(a+"//fonts.googleapis.com/css?family=")})[0],b=b.filter(function(b){return 0==b.name.indexOf(a+"//fonts.gstatic.com/s/")}).reduce(function(a,b){return b.duration>a.duration?b:a},{duration:0});
c&&0<c.startTime&&0<c.responseEnd&&(g.me("wfcs",ve(c.startTime)),g.me("wfce",ve(c.responseEnd)));b&&0<b.startTime&&0<b.responseEnd&&(g.me("wffs",ve(b.startTime)),g.me("wffe",ve(b.responseEnd)))};
Ae=function(a){var b=he(a),c=ge(a),d=b._start,e;for(e in b)if(g.ua(e,"_")&&g.ia(b[e])){var h=e.slice(1);if(h in Oaa){var k=(0,g.ye)(b[e],function(a){return Math.round(a-d)});
c["all_"+h]=k.join()}delete b[e]}h=!!c.ap;if(k=g.p("yt.timing.reportbuilder_")){if(k=k(b,c,a))ze(k,h),te(a)}else{var l=g.v("CSI_SERVICE_NAME","youtube"),k={v:2,s:l,action:g.v((a||"")+"TIMING_ACTION",void 0)},n=c.srt;delete c.srt;void 0===b.srt&&(n||0===n||(n=ee.timing||{},n=Math.max(0,n.responseStart-n.navigationStart),(0,window.isNaN)(n)&&c.pt&&(n=c.pt)),n||0===n)&&(c.srt=Math.round(n));if(c.h5jse){var u=window.location.protocol+g.p("ytplayer.config.assets.js");(u=ee.getEntriesByName?ee.getEntriesByName(u)[0]:
null)?c.h5jse=Math.round(c.h5jse-u.responseEnd):delete c.h5jse}b.aft=xe(a);Paa(a)&&"youtube"==l&&(oe("yt_lt","hot_bg",a),l=b.vc,u=b.pbs,delete b.aft,c.aft=Math.round(u-l));for(var w in c)"_"!=w.charAt(0)&&(k[w]=c[w]);b.ps=(0,g.zd)();c={};w=[];for(e in b)"_"!=e.charAt(0)&&(l=Math.round(b[e]-d),g.Pc("enable_negative_ticks")||(l=Math.max(l,0)),c[e]=l,w.push(e+"."+l));k.rt=w.join(",");(b=g.p("ytdebug.logTiming"))&&b(k,c);g.Pc("navigation_only_csi_reset")||te(a);ze(k,h,a);g.Ud(Qaa,new Vd(c.aft+(n||0)))}};
g.le=function(a,b){if(!Be(b)||!g.Pc("navigation_only_csi_reset")&&!b){var c=g.v((b||"")+"TIMING_ACTION",void 0),d=he(b);if(g.p("yt.timing."+(b||"")+"ready_")&&c&&d._start&&xe(b))if(a||b)Ae(b);else{var c=!0,e=g.v("TIMING_WAIT",[]);if(e.length)for(var h=0,k=e.length;h<k;++h)if(!(e[h]in d)){c=!1;break}c&&Ae(b)}}};
ze=function(a,b,c){if(g.Pc("debug_csi_data")){var d=g.p("yt.timing.csiData");d||(d=[],g.m("yt.timing.csiData",d,void 0));d.push({page:window.location.href,time:new Date,args:a})}var d="",e;for(e in a)d+="&"+e+"="+a[e];a="/csi_204?"+d.substring(1);window.navigator&&window.navigator.sendBeacon&&(!g.Pc("beacon_abandoned_only")||b)?g.Pd(a):g.Od(a);se(!0,c)};
Ce=function(a){g.m("yt.timing.ready_",a,void 0)};
ne=function(a){var b=De(a).nonce;if(!b){var c;a:{if(window.crypto&&window.crypto.getRandomValues)try{var d=Array(16),e=new window.Uint8Array(16);window.crypto.getRandomValues(e);for(b=0;b<d.length;b++)d[b]=e[b];c=d;break a}catch(h){}c=Array(16);for(d=0;16>d;d++){e=(0,g.E)();for(b=0;b<e%23;b++)c[d]=Math.random();c[d]=Math.floor(256*Math.random())}if(Ee)for(d=1,e=0;e<Ee.length;e++)c[d%16]=c[d%16]^c[(d-1)%16]/4^Ee.charCodeAt(e),d++}d=[];for(e=0;e<c.length;e++)d.push("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_".charAt(c[e]&
63));b=d.join("");De(a).nonce=b}return b};
he=function(a){return De(a).tick};
ge=function(a){return De(a).info};
ie=function(a){a=De(a);"gel"in a||(a.gel={});return a.gel};
De=function(a){return g.p("ytcsi."+(a||"")+"data_")||re(a)};
re=function(a){var b={tick:{},info:{}};g.m("ytcsi."+(a||"")+"data_",b,void 0);return b};
Be=function(a){return!!g.p("yt.timing."+(a||"")+"pingSent_")};
se=function(a,b){g.m("yt.timing."+(b||"")+"pingSent_",a,void 0)};
Fe=function(a){if(!Be(void 0)){if(!g.Pc("send_empty_timing")){var b=g.v("CSI_SERVICE_NAME","youtube");if(!g.v("TIMING_ACTION",void 0)||!b)return}g.me("aa",void 0,void 0);oe("ap",1,void 0);oe("yt_fss",a,void 0);Ae(void 0)}};
Paa=function(a){var b=he(a),c=b.pbr,d=b.vc,b=b.pbs;return c&&d&&b&&c<d&&d<b&&1==ge(a).yt_pvis};
Laa=function(){switch(g.Oc()){case "hidden":return 0;case "visible":return 1;case "prerender":return 2;case "unloaded":return 3}return-1};
g.Ge=function(a,b){g.Od("/gen_204?"+a,b)};
g.He=function(a){this.type="";this.state=this.source=this.data=this.currentTarget=this.relatedTarget=this.target=null;this.charCode=this.keyCode=0;this.shiftKey=this.ctrlKey=this.altKey=!1;this.rotation=this.clientY=this.clientX=0;this.scale=1;this.changedTouches=this.touches=null;if(a=a||window.event){this.event=a;for(var b in a)b in Raa||(this[b]=a[b]);this.scale=a.scale;this.rotation=a.rotation;(b=a.target||a.srcElement)&&3==b.nodeType&&(b=b.parentNode);this.target=b;if(b=a.relatedTarget)try{b=
b.nodeName?b:null}catch(c){b=null}else"mouseover"==this.type?b=a.fromElement:"mouseout"==this.type&&(b=a.toElement);this.relatedTarget=b;this.clientX=void 0!=a.clientX?a.clientX:a.pageX;this.clientY=void 0!=a.clientY?a.clientY:a.pageY;this.keyCode=a.keyCode?a.keyCode:a.which;this.charCode=a.charCode||("keypress"==this.type?this.keyCode:0);this.altKey=a.altKey;this.ctrlKey=a.ctrlKey;this.shiftKey=a.shiftKey;this.mn=a.pageX;this.nn=a.pageY}};
g.Je=function(a,b,c,d){a.addEventListener&&("mouseenter"!=b||"onmouseenter"in window.document?"mouseleave"!=b||"onmouseenter"in window.document?"mousewheel"==b&&"MozBoxSizing"in window.document.documentElement.style&&(b="MozMousePixelScroll"):b="mouseout":b="mouseover");return g.Qa(g.Ie,function(e){return e[0]==a&&e[1]==b&&e[2]==c&&e[4]==!!d})};
g.F=function(a,b,c,d){if(!a||!a.addEventListener&&!a.attachEvent)return"";d=!!d;var e=g.Je(a,b,c,d);if(e)return e;var e=++Ke.count+"",h=!("mouseenter"!=b&&"mouseleave"!=b||!a.addEventListener||"onmouseenter"in window.document),k;k=h?function(d){d=new g.He(d);if(!g.Kc(d.relatedTarget,function(b){return b==a},!0))return d.currentTarget=a,d.type=b,c.call(a,d)}:function(b){b=new g.He(b);
b.currentTarget=a;return c.call(a,b)};
k=g.ub(k);a.addEventListener?("mouseenter"==b&&h?b="mouseover":"mouseleave"==b&&h?b="mouseout":"mousewheel"==b&&"MozBoxSizing"in window.document.documentElement.style&&(b="MozMousePixelScroll"),a.addEventListener(b,k,d)):a.attachEvent("on"+b,k);g.Ie[e]=[a,b,c,k,d];return e};
g.G=function(a){a&&("string"==typeof a&&(a=[a]),(0,g.y)(a,function(a){if(a in g.Ie){var c=g.Ie[a],d=c[0],e=c[1],h=c[3],c=c[4];d.removeEventListener?d.removeEventListener(e,h,c):d.detachEvent&&d.detachEvent("on"+e,h);delete g.Ie[a]}}))};
g.Le=function(a){a=a||window.event;a.returnValue=!1;a.preventDefault&&a.preventDefault()};
g.Ne=function(){if(null==g.p("_lact",window)){var a=(0,window.parseInt)(g.v("LACT"),10),a=(0,window.isFinite)(a)?(0,g.E)()-Math.max(a,0):-1;g.m("_lact",a,window);-1==a&&Me();g.F(window.document,"keydown",Me);g.F(window.document,"keyup",Me);g.F(window.document,"mousedown",Me);g.F(window.document,"mouseup",Me);g.x("page-mouse",Me);g.x("page-scroll",Me);g.x("page-resize",Me)}};
Me=function(){null==g.p("_lact",window)&&(g.Ne(),g.p("_lact",window));var a=(0,g.E)();g.m("_lact",a,window);g.z("USER_ACTIVE")};
g.Oe=function(){var a=g.p("_lact",window);return null==a?-1:Math.max((0,g.E)()-a,0)};
Pe=function(a){a=a||{};this.url=a.url||"";this.urlV9As2=a.url_v9as2||"";this.args=a.args||g.Ua(Saa);this.assets=a.assets||{};this.attrs=a.attrs||g.Ua(Taa);this.params=a.params||g.Ua(Uaa);this.minVersion=a.min_version||"8.0.0";this.fallback=a.fallback||null;this.fallbackMessage=a.fallbackMessage||null;this.html5=!!a.html5;this.disable=a.disable||{};this.loaded=!!a.loaded;this.messages=a.messages||{}};
g.Qe=function(a){a instanceof Pe||(a=new Pe(a));return a};
Se=function(){return null!=g.Re};
g.Te=function(){return g.Re?g.Re.invoke():null};
Ue=function(){return(0,window.parseInt)(g.v("DCLKSTAT",0),10)};
g.Ve=function(a){this.A=a||{cookie:""}};
g.Xe=function(a){a=(a.A.cookie||"").split(g.We);for(var b=[],c=[],d,e,h=0;e=a[h];h++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
g.Ze=function(a,b,c,d){g.Ye.set(""+a,b,c,"/",d||"youtube.com")};
g.bf=function(a,b,c){var d=g.v("VALID_SESSION_TEMPDATA_DOMAINS",[]),e=g.Gd(window.location.href);e&&d.push(e);e=g.Gd(a);if(g.Ia(d,e)||!e&&g.ua(a,"/"))if(a=g.Hd(a),a=g.Id(a))c?(c=(0,window.parseInt)(c,10),(0,window.isFinite)(c)&&0<c&&($e(a,b,c),af(b))):($e(a,b),af(b))};
$e=function(a,b,c){a="ST-"+g.Da(a).toString(36);c=c||5;b=b?g.Md(b):"";g.Ze(a,b,c)};
af=function(a){if(a){a=a.itct||a.ved;var b=g.p("yt.logging.screenreporter.storeParentElement");a&&b&&b(new g.rd(a))}};
g.cf=function(a,b,c){c=c||"";g.fc(window.location,g.Nd(a,b||{})+c)};
g.df=function(a,b){b&&g.bf(a,b);(window.ytspf||{}).enabled?window.spf.navigate(a):g.cf(a)};
g.ef=function(a,b,c){var d=g.v("EVENT_ID");d&&(b||(b={}),b.ei||(b.ei=d));b&&g.bf(a,b);if(c)return!1;g.df(a);return!0};
g.ff=function(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a};
g.gf=function(a,b){a.style.height=g.ff(b,!0)};
g.hf=function(a,b){a.style.width=g.ff(b,!0)};
g.kf=function(){this.A=this.minor=this.major=0;this.C="";var a=g.p("window.navigator.plugins"),b=g.p("window.navigator.mimeTypes"),a=a&&a["Shockwave Flash"],b=b&&b["application/x-shockwave-flash"],b=a&&b&&b.enabledPlugin&&a.description||"";if(a=b){var c=a.indexOf("Shockwave Flash");0<=c&&(a=a.substr(c+15));for(var c=a.split(" "),d="",a="",e=0,h=c.length;e<h;e++)if(d)if(a)break;else a=c[e];else d=c[e];d=d.split(".");c=(0,window.parseInt)(d[0],10)||0;d=(0,window.parseInt)(d[1],10)||0;e=0;if("r"==a.charAt(0)||
"d"==a.charAt(0))e=(0,window.parseInt)(a.substr(1),10)||0;a=[c,d,e]}else a=[0,0,0];this.C=b;b=a;this.major=b[0];this.minor=b[1];this.A=b[2];if(0>=this.major){var k,l,n,u;if(g.jf)try{k=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(w){k=null}else n=window.document.body,u=window.document.createElement("object"),u.setAttribute("type","application/x-shockwave-flash"),k=n.appendChild(u);if(k&&"GetVariable"in k)try{l=k.GetVariable("$version")}catch(w){l=""}n&&u&&n.removeChild(u);(k=l||
"")?(k=k.split(" ")[1].split(","),k=[(0,window.parseInt)(k[0],10)||0,(0,window.parseInt)(k[1],10)||0,(0,window.parseInt)(k[2],10)||0]):k=[0,0,0];this.major=k[0];this.minor=k[1];this.A=k[2]}};
g.lf=function(a,b,c,d){b="string"==typeof b?b.split("."):[b,c,d];b[0]=(0,window.parseInt)(b[0],10)||0;b[1]=(0,window.parseInt)(b[1],10)||0;b[2]=(0,window.parseInt)(b[2],10)||0;return a.major>b[0]||a.major==b[0]&&a.minor>b[1]||a.major==b[0]&&a.minor==b[1]&&a.A>=b[2]};
g.mf=function(a){return-1<a.C.indexOf("Gnash")&&-1==a.C.indexOf("AVM2")||9==a.major&&1==a.minor||9==a.major&&0==a.minor&&1==a.A?!1:9<=a.major};
g.nf=function(a){return-1<window.navigator.userAgent.indexOf("Sony/COM2")&&!g.lf(a,9,1,58)?!1:!0};
g.of=function(a,b,c){if(b){a=g.ka(a)?g.uc(a):a;var d=g.Ua(c.attrs);d.tabindex=0;var e=g.Ua(c.params);e.flashvars=g.Md(c.args);if(g.jf){d.classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000";e.movie=b;b=window.document.createElement("object");for(var h in d)b.setAttribute(h,d[h]);for(h in e)d=window.document.createElement("param"),d.setAttribute("name",h),d.setAttribute("value",e[h]),b.appendChild(d)}else{d.type="application/x-shockwave-flash";d.src=b;b=window.document.createElement("embed");b.setAttribute("name",
d.id);for(h in d)b.setAttribute(h,d[h]);for(h in e)b.setAttribute(h,e[h])}e=window.document.createElement("div");e.appendChild(b);a.innerHTML=e.innerHTML}};
g.pf=function(a,b){var c=a.match(Vaa);window.spf.style.load(a,c?c[1]:"",b)};
qf=function(a){g.mb.call(this);this.A=[];this.C=a||this};
rf=function(a,b,c,d){d=g.ub((0,g.q)(d,a.C));b.addEventListener(c,d);a.A.push({target:b,name:c,Nb:d})};
sf=function(a){for(;a.A.length;){var b=a.A.pop();b.target.removeEventListener(b.name,b.Nb)}};
vf=function(a,b){g.mb.call(this);this.K=this.D=a;this.ha=b;this.H=!1;this.api={};this.la=this.T=null;this.X=new g.qb;g.pb(this,this.X);this.B={};this.G=this.Ua=this.C=this.hb=this.A=null;this.aa=!1;this.R=this.F=this.M=this.P=null;this.Xa={};this.Hb=["onReady"];this.ea=new qf(this);g.pb(this,this.ea);this.kb=null;this.Bb=window.NaN;this.ga={};tf(this);this.ie("onDetailedError",(0,g.q)(this.NI,this));this.ie("onTabOrderChange",(0,g.q)(this.hy,this));this.ie("onTabAnnounce",(0,g.q)(this.hp,this));this.ie("WATCH_LATER_VIDEO_ADDED",
(0,g.q)(this.RI,this));this.ie("WATCH_LATER_VIDEO_REMOVED",(0,g.q)(this.SI,this));g.uf||(this.ie("onMouseWheelCapture",(0,g.q)(this.vI,this)),this.ie("onMouseWheelRelease",(0,g.q)(this.wI,this)));this.ie("onAdAnnounce",(0,g.q)(this.hp,this));this.Y=new qf(this);g.pb(this,this.Y);this.bb=!1;this.ab=null};
xf=function(a,b){a.hb=b;a.A=b.clone();a.C=a.A.attrs.id||a.C;"video-player"==a.C&&(a.C=a.ha,a.A.attrs.id=a.ha);a.K.id==a.C&&(a.C+="-player",a.A.attrs.id=a.C);a.A.args.enablejsapi="1";a.A.args.playerapiid=a.ha;a.Ua||(a.Ua=wf(a,a.A.args.jsapicallback||"onYouTubePlayerReady"));a.A.args.jsapicallback=null;var c=a.A.attrs.width;c&&g.hf(a.K,Number(c)||c);(c=a.A.attrs.height)&&g.gf(a.K,Number(c)||c)};
yf=function(a){a.A.loaded||(a.A.loaded=!0,"0"!=a.A.args.autoplay?a.api.loadVideoByPlayerVars(a.A.args):a.api.cueVideoByPlayerVars(a.A.args))};
zf=function(a){if(!g.da(a.A.disable.flash)){var b=a.A.disable,c;c=g.lf(g.kf.getInstance(),a.A.minVersion);b.flash=!c}return!a.A.disable.flash};
Cf=function(a,b){if((!b||(5!=(Waa[b.errorCode]||5)?0:-1!=Xaa.indexOf(b.errorCode)))&&zf(a)){var c=Af(a);c&&c.stopVideo&&c.stopVideo();var d=a.A;c&&c.getUpdatedConfigurationData&&(c=c.getUpdatedConfigurationData(),d=g.Qe(c));d.args.autoplay=1;d.args.html5_unavailable="1";xf(a,d);Bf(a,"flash")}};
Bf=function(a,b){if(!a.isDisposed()){if(!b){var c;if(!(c=!a.A.html5&&zf(a))){if(!g.da(a.A.disable.html5)){var d;c=!0;void 0!=a.A.args.deviceHasDisplay&&(c=a.A.args.deviceHasDisplay);if(2.2==Df)d=!0;else{a:{var e=c;c=g.p("yt.player.utils.videoElement_");c||(c=window.document.createElement("video"),g.m("yt.player.utils.videoElement_",c,void 0));try{if(c.canPlayType)for(var e=e?Yaa:Zaa,h=0;h<e.length;h++)if(c.canPlayType(e[h])){d=null;break a}d="fmt.noneavailable"}catch(k){d="html5.missingapi"}}d=!d}d&&
(d=Ef(a)||a.A.assets.js);a.A.disable.html5=!d;d||(a.A.args.html5_unavailable="1")}c=!!a.A.disable.html5}b=c?zf(a)?"flash":"unsupported":"html5"}("flash"==b?a.TO:a.UO).call(a)}};
Ef=function(a){var b=!0,c=Af(a);c&&a.A&&(a=a.A,b=g.A(c,"version")==a.assets.js);return b&&!!g.p("yt.player.Application.create")};
Af=function(a){var b=g.C(a.C);!b&&a.K&&a.K.querySelector&&(b=a.K.querySelector("#"+a.C));return b};
Ff=function(a,b,c){var d=b[c];return function(){try{return a.kb=null,d.apply(b,arguments)}catch(e){"Bad NPObject as private data!"!=e.message&&"sendAbandonmentPing"!=c&&(e.message+=" ("+c+")",a.kb=e,g.zb(e,"WARNING"))}}};
tf=function(a){a.H=!1;if(a.la)for(var b in a.B)a.la(b,a.B[b]);for(var c in a.ga)g.xb((0,window.parseInt)(c,10));a.ga={};a.T=null;a.la=null;for(var d in a.api)a.api[d]=null;a.api.addEventListener=(0,g.q)(a.ie,a);a.api.removeEventListener=(0,g.q)(a.aN,a);a.api.destroy=(0,g.q)(a.dispose,a);a.api.getLastError=(0,g.q)(a.Iz,a);a.api.getPlayerType=(0,g.q)(a.Yz,a);a.api.getCurrentVideoConfig=(0,g.q)(a.ez,a);a.api.loadNewVideoConfig=(0,g.q)(a.Co,a);a.api.isReady=(0,g.q)(a.gP,a)};
wf=function(a,b){var c=b;if("string"==typeof b){if(a.Xa[b])return a.Xa[b];c=function(){var a=g.p(b);a&&a.apply(g.ea,arguments)};
a.Xa[b]=c}return c?c:null};
$aa=function(a,b){var c="ytPlayer"+b+a.ha;a.B[b]=c;g.ea[c]=function(c){var e=g.vb(function(){a.isDisposed()||(a.X.Fa(b,c),g.Sa(a.ga,String(e)))},0);
g.Ta(a.ga,String(e),!0)};
return c};
Gf=function(a){return(a=Af(a))?"div"==a.tagName.toLowerCase()?"html5":"flash":null};
Hf=function(a){g.me("dcp");a.cancel();tf(a);a.G=null;a.A&&(a.A.loaded=!1);var b=Af(a);"html5"==Gf(a)?a.M=b:b&&b.destroy&&b.destroy();g.Gc(a.D);sf(a.ea);a.F=null;a.R=null};
g.Kf=function(a,b){a=g.ka(a)?g.uc(a):a;b=g.Qe(b);var c=g.If+"_"+g.qa(a),d=g.Jf[c];if(d)return d.Co(b),d.api;d=new vf(a,c);g.Jf[c]=d;g.z("player-added",d.api);g.nb(d,g.r(aba,d));g.vb(function(){d.Co(b)},0);
return d.api};
aba=function(a){g.Jf[a.getId()]=null};
g.Lf=function(a){a=g.C(a);if(!a)return null;var b=g.If+"_"+g.qa(a),c=g.Jf[b];c||(c=new vf(a,b),g.Jf[b]=c);return c.api};
g.Mf=function(){return g.B(g.C("page-container"),"remote-connected")};
bba=function(){g.m("yt.abuse.botguardInitialized",Se,void 0);g.m("yt.abuse.invokeBotguard",g.Te,void 0);g.m("yt.abuse.dclkstatus.checkDclkStatus",Ue,void 0);g.m("yt.player.exports.navigate",g.ef,void 0);g.m("yt.player.embed",g.Kf,void 0);g.m("yt.player.getPlayerByElement",g.Lf,void 0);g.m("yt.util.activity.init",g.Ne,void 0);g.m("yt.util.activity.getTimeSinceActive",g.Oe,void 0);g.m("yt.util.activity.setTimestamp",Me,void 0);var a=g.p("ytplayer.config");Nf(a);g.p("ytspf.enabled")&&(Of=g.wb(Pf,5E3),
(a=g.Qf())?(a.addEventListener("onReady",Pf),a.addEventListener("onStateChange",Pf)):Rf("unable to init PP monitor"))};
Nf=function(a){for(var b in g.Jf){var c=g.Jf[b];c&&c.cancel()}if(a=a||null){b=g.Qf();var d=!0,c=g.Sf;g.Sf=null;b&&b.getVideoData&&c&&(d=b.getVideoData(),d=!!c.fullscreen||d.video_id!=a.args.video_id||d.list!=a.args.list||d.video_id!=c.videoId||d.list!=c.listId);d?(Tf="",g.Kf("player-api",a)):b.playVideo();a=g.Qe(a);a.loaded=!0}Pf();g.m("ytplayer.config",a,void 0)};
g.Qf=function(){var a=g.p("yt.player.getPlayerByElement");return a?a("player-api"):null};
Pf=function(){var a=g.Qf();if(a){var b;b=g.C("player");b=!b||g.B(b,"off-screen");var c=1==(a&&a.isReady()?a.getPlayerState():void 0),d="watch"==g.v("PAGE_NAME"),e=g.Mf();!c||d||e||(Rf("PP playing off watch (paused)"),a.pauseVideo());b&&d?Rf("PP off-screen on watch"):b||d||Rf("PP !off-screen off watch")}};
Rf=function(a){var b=g.v("PAGE_NAME");b&&(b=[b,Tf,g.p("_spf_state.nav-counter")],a+="("+b.join(",")+")",g.m("yt.www.persistentplayer.issue",a,void 0),g.zb(Error(a),"WARNING"))};
g.Uf=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.$f=!1;this.kv=!0};
g.Vf=function(a,b){g.Uf.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.charCode=this.keyCode=this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.rn=!1;this.sb=null;a&&this.init(a,b)};
g.Xf=function(a){return!(!a||!a[Wf])};
dba=function(a,b,c,d,e){this.listener=a;this.A=null;this.src=b;this.type=c;this.vh=!!d;this.md=e;this.key=++cba;this.Tg=this.Oi=!1};
Yf=function(a){a.Tg=!0;a.listener=null;a.A=null;a.src=null;a.md=null};
Zf=function(a){this.src=a;this.A={};this.C=0};
g.ag=function(a,b,c,d,e,h){var k=b.toString();b=a.A[k];b||(b=a.A[k]=[],a.C++);var l=$f(b,c,e,h);-1<l?(a=b[l],d||(a.Oi=!1)):(a=new dba(c,a.src,k,!!e,h),a.Oi=d,b.push(a));return a};
bg=function(a,b){var c=b.type;if(!(c in a.A))return!1;var d=g.Ka(a.A[c],b);d&&(Yf(b),0==a.A[c].length&&(delete a.A[c],a.C--));return d};
g.cg=function(a,b,c,d,e){a=a.A[b.toString()];b=-1;a&&(b=$f(a,c,d,e));return-1<b?a[b]:null};
$f=function(a,b,c,d){for(var e=0;e<a.length;++e){var h=a[e];if(!h.Tg&&h.listener==b&&h.vh==!!c&&h.md==d)return e}return-1};
g.dg=function(a,b,c,d,e){if(g.ia(b)){for(var h=0;h<b.length;h++)g.dg(a,b[h],c,d,e);return null}c=g.eg(c);return g.Xf(a)?a.O(b,c,d,e):g.fg(a,b,c,!1,d,e)};
g.fg=function(a,b,c,d,e,h){if(!b)throw Error("Invalid event type");var k=!!e,l=g.gg(a);l||(a[hg]=l=new Zf(a));c=g.ag(l,b,c,d,e,h);if(c.A)return c;d=eba();c.A=d;d.src=a;d.listener=c;if(a.addEventListener)a.addEventListener(b.toString(),d,k);else if(a.attachEvent)a.attachEvent(ig(b.toString()),d);else throw Error("addEventListener and attachEvent are unavailable.");jg++;return c};
eba=function(){var a=fba,b=kg?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);
if(!c)return c};
return b};
g.lg=function(a,b,c,d,e){if(g.ia(b))for(var h=0;h<b.length;h++)g.lg(a,b[h],c,d,e);else c=g.eg(c),g.Xf(a)?a.Va(b,c,d,e):a&&(a=g.gg(a))&&(b=g.cg(a,b,c,!!d,e))&&g.mg(b)};
g.mg=function(a){if(g.ma(a)||!a||a.Tg)return!1;var b=a.src;if(g.Xf(b))return bg(b.Y,a);var c=a.type,d=a.A;b.removeEventListener?b.removeEventListener(c,d,a.vh):b.detachEvent&&b.detachEvent(ig(c),d);jg--;(c=g.gg(b))?(bg(c,a),0==c.C&&(c.src=null,b[hg]=null)):Yf(a);return!0};
ig=function(a){return a in ng?ng[a]:ng[a]="on"+a};
pg=function(a,b,c,d){var e=!0;if(a=g.gg(a))if(b=a.A[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var h=b[a];h&&h.vh==c&&!h.Tg&&(h=og(h,d),e=e&&!1!==h)}return e};
og=function(a,b){var c=a.listener,d=a.md||a.src;a.Oi&&g.mg(a);return c.call(d,b)};
fba=function(a,b){if(a.Tg)return!0;if(!kg){var c=b||g.p("window.event"),d=new g.Vf(c,this),e=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var h=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(n){h=!0}if(h||void 0==c.returnValue)c.returnValue=!0}c=[];for(h=d.currentTarget;h;h=h.parentNode)c.push(h);for(var h=a.type,k=c.length-1;!d.$f&&0<=k;k--){d.currentTarget=c[k];var l=pg(c[k],h,!0,d),e=e&&l}for(k=0;!d.$f&&k<c.length;k++)d.currentTarget=c[k],l=pg(c[k],h,!1,d),e=e&&l}return e}return og(a,new g.Vf(b,
this))};
g.gg=function(a){a=a[hg];return a instanceof Zf?a:null};
g.eg=function(a){if(g.na(a))return a;a[qg]||(a[qg]=function(b){return a.handleEvent(b)});
return a[qg]};
g.rg=function(){g.mb.call(this);this.Y=new Zf(this);this.qx=this;this.vo=null};
sg=function(a,b,c,d){b=a.Y.A[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,h=0;h<b.length;++h){var k=b[h];if(k&&!k.Tg&&k.vh==c){var l=k.listener,n=k.md||k.src;k.Oi&&bg(a.Y,k);e=!1!==l.call(n,d)&&e}}return e&&0!=d.kv};
g.tg=function(a,b,c){if(g.na(a))c&&(a=(0,g.q)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,g.q)(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:g.ea.setTimeout(a,b||0)};
g.ug=function(a){g.ea.clearTimeout(a)};
g.vg=function(a,b,c){g.mb.call(this);this.A=a;this.B=b||0;this.C=c;this.Hc=(0,g.q)(this.Sl,this)};
lba=function(){wg++;var a=g.yc(),b=new g.Yd(0,0,a.width,a.height);oe("vps",a.width+"."+a.height);g.me("vpc");var a=window.document.querySelectorAll(".yt-lockup-thumbnail img[data-ytimg]"),c=a.length,d=[],e=!0;xg.start();for(var h=0;h<c;h++){var k=a[h];if(yg(k,b)){var l=gba(k);l.then(hba);d.push(l);zg.push(l);k.loadTime||(e=!1)}}e&&oe("yt_eil",1);oe("vpni",d.length);g.me("vpcc");b=g.cd(d).then(iba);g.ed(b,jba);b.then(kba);zg.push(b);return b};
kba=function(){xg.stop()};
jba=function(){g.me("vpr")};
yg=function(a,b){for(var c=a,d=window.document.body;c!=d;){var e=g.Mc(c);if(e in Ag)break;var h=window.getComputedStyle(c);if("none"==h.display||"hidden"==h.visibility)return!1;h=c.getBoundingClientRect();if(!(b.left<=h.left+h.width&&h.left<=b.left+b.width&&b.top<=h.top+h.height&&h.top<=b.top+b.height))return!1;Ag[e]=!0;c=c.parentElement}return!0};
iba=function(a){for(var b=g.yc(),b=new g.Yd(0,0,b.width,b.height),c=0,d=0,e=a.length;d<e;d++){var h=a[d].time;yg(a[d].C,b)&&c<h&&(c=h)}return c};
gba=function(a){var b=wg;return new g.Yc(function(c,d){var e={C:a,time:0};if(a.loadTime)e.time=(0,window.parseInt)(a.loadTime,10),c(e);else{var h=g.F(a,"load",function(){wg!=b&&(g.G(h),d());if(a.loadTime){var k=(0,window.parseInt)(a.loadTime,10);g.G(h);e.time=k;c(e)}});
Bg.push(h)}})};
hba=function(a){xg.start();oe("vpil",++Cg);a=a.time;Dg<a&&(Dg=a,g.me("lim",a))};
mba=function(){g.me("vptl",Dg);g.me("vpl",Dg)};
Fg=function(){g.me("ol");window.requestAnimationFrame&&!window.document.hidden?window.requestAnimationFrame(function(){(0,window.setTimeout)(function(){g.me("cpt")},0)}):window.document.hidden?g.me("cpt"):(0,window.setTimeout)(function(){g.me("cpt")},0);
nba();g.v("CSI_VIEWPORT")&&(Eg=lba(),Eg.then(function(a){g.me("vpl",a);Eg=null},function(){}))};
nba=function(){Gg("init");var a=g.v("PAGE_NAME",void 0);a&&Gg("init-"+a)};
Gg=function(a){g.Jb()?Hg.push(g.Kb(g.r(g.Ib,a),0)):g.z(a)};
Ig=function(){g.Nb(Hg);Hg.length=0;for(var a=zg.length,b=0;b<a;b++)zg[b].cancel();Dg=Cg=zg.length=0;Ag={};g.G(Bg);Bg.length=0;Eg&&(Eg.cancel(),Eg=null);(a=g.v("PAGE_NAME",void 0))&&g.Ib("dispose-"+a);g.Ib("dispose")};
oba=function(){Fg()};
pba=function(){g.v("TIMING_REPORT_ON_UNLOAD")&&g.le(!0);Fe("u");Ig();g.Ib("pageunload")};
Jg=function(){Me()};
Kg=function(){window.yt_spf_loaded_history=!0;Me()};
Pg=function(){Lg=1;Mg=Ng=0;g.v("TIMING_REPORT_ON_UNLOAD")&&g.le(!0);Fe("n");te();pe("n");fe("nr");Og(qba);g.Ib("navigate")};
Tg=function(a){a=a.detail.part||a.detail.partial;g.me("nc"+Ng);++Ng;if(!a.data||!a.data.deferDispose){var b=1==Lg;Lg=2;b?(Og(rba),Qg()):Og(sba);if(b=a.data&&a.data.swfcfg)Rg(a.timing,b.args),Sg(b)}};
Ug=function(){g.me("np"+Mg);++Mg};
Vg=function(a){a=a.detail.response;var b=1==Lg;Lg=3;b&&(Og(tba),Qg());if(b=a.data&&a.data.swfcfg)Rg(a.timing,b.args),Sg(b)};
Yg=function(a){g.me("nd");a=a.detail.response;g.Wg=a.cacheKey;a=a.timing;var b=window._spf_state;oe("yt_nav",b&&b["nav-counter"]||0);pe("ne",a.responseStart);oe("srt",Math.max(0,a.responseStart-a.navigationStart));oe("yt_lt",a.spfCached?"hot":"warm");oe("yt_pft",+!!a.spfPrefetched);g.me("pfs",a.fetchStart);g.me("pfrs",a.responseStart);"redirectStart"in a&&ue(a);Og(Xg);window.document.getElementById("content").style.height="";Fg();Lg=0};
Zg=function(a){var b=a.detail.url;if(a=a.detail.err)a.message&&(a.message+=" (url: "+b+")"),g.zb(a)};
$g=function(a){g.Ge(g.Md({spfreload:"1",url:a.detail.url,reason:a.detail.reason}))};
vba=function(){uba();g.tb("SERVED_VIA_SPF_HISTORY",!!window.yt_spf_loaded_history);window.yt_spf_loaded_history=!1};
wba=function(){};
Qg=function(){var a=window.document.getElementById("content");-1<a.className.indexOf("spf-animate")&&(a.style.height=a.clientHeight+"px");Ig();var a=g.v("TIMING_ACTION"),b;for(b in g.sb)delete g.sb[b];g.tb("PREVIOUS_ACTION",a);g.m("ytplayer.config",null,void 0);if((b=g.Qf())&&b.stopVideo){if(b.stopVideo(),b=b.getLastError())Tf=b,(b=g.C("movie_player"))&&b.stopVideo?(b.stopVideo(),Tf="recovered"):Tf="missing2"}else Tf="missing";Pf()};
Sg=function(a){"cfg"in he(void 0)||g.me("cfg");Nf(a)};
Og=function(a){var b=window.document.getElementById("progress");b||(b=window.document.createElement("div"),b.id="progress",b.appendChild(window.document.createElement("dt")),b.appendChild(window.document.createElement("dd")),window.document.body.appendChild(b));g.Mb(ah);ah=g.Lb(function(){var c=a[0],d=a[1],e=a[2];b.className="";var h=b.style;h.transitionDuration=h.webkitTransitionDuration=c+"ms";h.width=d+"%";g.xb(bh);bh=g.vb(function(){b.className=e},c)},0)};
uba=function(){var a=Xg[0]+50;g.xb(bh);bh=g.vb(function(){var a=window.document.getElementById("progress");a&&a.parentNode.removeChild(a)},a)};
Rg=function(a,b){var c=a&&a.spfCached,d=a&&a.spfPrefetched,e=[];c&&!d&&(0,g.y)(xba,function(a){a in b&&(delete b[a],e.push(a))});
g.v("EXP_DEBUG_PREFETCH")&&(e.sort(),c={a:"removeNonCacheableVideoVars",cached:c,prefetched:d,deleted:e.join("")},g.Ge(g.Md(c)))};
yba=function(a){!g.ch||g.dh||g.eh||g.fh||!a.pushManager||("default"==window.Notification.permission?g.v("LOGGED_IN",void 0)&&a.pushManager.subscribe({userVisibleOnly:!0}).then(function(){gh()},function(){gh()}):window.navigator.serviceWorker.controller.postMessage({type:"notifications_check_user",
data:g.v("ID_TOKEN")}))};
gh=function(){window.navigator.serviceWorker.controller.postMessage({type:"notifications_register",data:g.v("ID_TOKEN")})};
zba=function(){var a="/sw.js",b=g.v("SERVICE_WORKER_VFL",void 0);b&&(a+="?vfl="+b);window.navigator.serviceWorker.register(a,{scope:"/"});g.Pc("service_worker_push_enabled")&&window.navigator.serviceWorker.ready.then(yba)};
Aba=function(a){a&&window.navigator.serviceWorker.register("/sw.js?0",{scope:"/"})};
hh=function(){g.Ob.call(this,"www/base");this.B=0};
ih=function(a){(a=a.detail.name)&&Rb(a)};
g.ba=[];g.jh=g.jh||{};g.ea=this;pa="closure_uid_"+(1E9*Math.random()>>>0);aaa=0;g.E=Date.now||function(){return+new Date};ra[" "]=g.fa;g.t(g.ta,Error);g.ta.prototype.name="CustomError";var eaa,faa,gaa,haa,iaa,jaa,daa;g.Aa=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
eaa=/&/g;faa=/</g;gaa=/>/g;haa=/"/g;iaa=/'/g;jaa=/\x00/g;daa=/[\x00&<>"']/;g.kh=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};
g.Bba=2147483648*Math.random()|0;g.Ha=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;
if(g.ka(a))return g.ka(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
g.Cba=Array.prototype.lastIndexOf?function(a,b,c){return Array.prototype.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;
0>c&&(c=Math.max(0,a.length+c));if(g.ka(a))return g.ka(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};
g.y=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.ka(a)?a.split(""):a,h=0;h<d;h++)h in e&&b.call(c,e[h],h,a)};
g.lh=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],h=0,k=g.ka(a)?a.split(""):a,l=0;l<d;l++)if(l in k){var n=k[l];
b.call(c,n,l,a)&&(e[h++]=n)}return e};
g.ye=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),h=g.ka(a)?a.split(""):a,k=0;k<d;k++)k in h&&(e[k]=b.call(c,h[k],k,a));
return e};
g.mh=Array.prototype.reduce?function(a,b,c,d){d&&(b=(0,g.q)(b,d));return Array.prototype.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;
(0,g.y)(a,function(c,k){e=b.call(d,e,c,k,a)});
return e};
g.nh=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.ka(a)?a.split(""):a,h=0;h<d;h++)if(h in e&&b.call(c,e[h],h,a))return!0;
return!1};
g.oh=Array.prototype.every?function(a,b,c){return Array.prototype.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.ka(a)?a.split(""):a,h=0;h<d;h++)if(h in e&&!b.call(c,e[h],h,a))return!1;
return!0};g.ph=g.Ma(!1);g.qh=g.Ma(!0);g.rh=g.Ma(null);var Va="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");a:{var sh=g.ea.navigator;if(sh){var th=sh.userAgent;if(th){g.Xa=th;break a}}g.Xa=""};var lb;bb.prototype.get=function(){var a;0<this.C?(this.C--,a=this.A,this.A=a.next,a.next=null):a=this.B();return a};var ib=new bb(function(){return new eb},function(a){a.reset()},100);
db.prototype.remove=function(){var a=null;this.A&&(a=this.A,this.A=this.A.next,this.A||(this.C=null),a.next=null);return a};
eb.prototype.set=function(a,b){this.pe=a;this.scope=b;this.next=null};
eb.prototype.reset=function(){this.next=this.scope=this.pe=null};var fb,gb=!1,hb=new db;g.mb.prototype.Md=!1;g.mb.prototype.isDisposed=function(){return this.Md};
g.mb.prototype.dispose=function(){this.Md||(this.Md=!0,this.U())};
g.mb.prototype.U=function(){if(this.Jb)for(;this.Jb.length;)this.Jb.shift()()};g.t(g.qb,g.mb);g.f=g.qb.prototype;g.f.subscribe=function(a,b,c){var d=this.rd[a];d||(d=this.rd[a]=[]);var e=this.D;this.A[e]=a;this.A[e+1]=b;this.A[e+2]=c;this.D=e+3;d.push(e);return e};
g.f.unsubscribe=function(a,b,c){if(a=this.rd[a]){var d=this.A;if(a=g.Ga(a,function(a){return d[a+1]==b&&d[a+2]==c}))return this.sd(a)}return!1};
g.f.sd=function(a){var b=this.A[a];if(b){var c=this.rd[b];0!=this.B?(this.C.push(a),this.A[a+1]=g.fa):(c&&g.Ka(c,a),delete this.A[a],delete this.A[a+1],delete this.A[a+2])}return!!b};
g.f.Fa=function(a,b){var c=this.rd[a];if(c){for(var d=Array(arguments.length-1),e=1,h=arguments.length;e<h;e++)d[e-1]=arguments[e];if(this.F)for(e=0;e<c.length;e++){var k=c[e];maa(this.A[k+1],this.A[k+2],d)}else{this.B++;try{for(e=0,h=c.length;e<h;e++)k=c[e],this.A[k+1].apply(this.A[k+2],d)}finally{if(this.B--,0<this.C.length&&0==this.B)for(;c=this.C.pop();)this.sd(c)}}return 0!=e}return!1};
g.f.clear=function(a){if(a){var b=this.rd[a];b&&((0,g.y)(b,this.sd,this),delete this.rd[a])}else this.A.length=0,this.rd={}};
g.f.ob=g.ca(1);g.f.U=function(){g.qb.L.U.call(this);this.clear();this.C.length=0};g.sb=window.yt&&window.yt.config_||window.ytcfg&&window.ytcfg.data_||{};g.m("yt.config_",g.sb,void 0);g.m("yt.tokens_",window.yt&&window.yt.tokens_||{},void 0);g.Ab=window.yt&&window.yt.msgs_||g.p("window.ytcfg.msgs")||{};g.m("yt.msgs_",g.Ab,void 0);g.zd=window.performance&&window.performance.timing&&window.performance.now?function(){return window.performance.timing.navigationStart+window.performance.now()}:function(){return(new Date).getTime()};
g.jf="Microsoft Internet Explorer"==window.navigator.appName;var Dba=g.p("yt.pubsub.instance_")||new g.qb;g.qb.prototype.subscribe=g.qb.prototype.subscribe;g.qb.prototype.unsubscribeByKey=g.qb.prototype.sd;g.qb.prototype.publish=g.qb.prototype.Fa;g.qb.prototype.clear=g.qb.prototype.clear;g.m("yt.pubsub.instance_",Dba,void 0);var Eb=g.p("yt.pubsub.subscribedKeys_")||{};g.m("yt.pubsub.subscribedKeys_",Eb,void 0);var Gb=g.p("yt.pubsub.topicToKeys_")||{};g.m("yt.pubsub.topicToKeys_",Gb,void 0);var Fb=g.p("yt.pubsub.isSynchronous_")||{};
g.m("yt.pubsub.isSynchronous_",Fb,void 0);var Db=g.p("yt.pubsub.skipSubId_")||null;g.m("yt.pubsub.skipSubId_",Db,void 0);g.f=g.Ob.prototype;g.f.nN=function(){this.Qj()||this.init()};
g.f.enable=function(){this.A=1;(0,g.y)("string"==typeof this.page?[this.page]:this.page,function(a){a&&(this.subscribe("init-"+a,this.nN,this),this.subscribe("dispose-"+a,this.dispose,this),g.v("PAGE_NAME")==a&&g.Pb(this))},this)};
g.f.init=function(){g.Mb(this.C);this.A=2;this.H&&this.H()};
g.f.Qj=function(){return 2==this.A};
g.f.dispose=function(){this.A=3;g.Mb(this.C);this.F&&this.F()};
g.f.disable=function(){this.A=4;this.clear();try{this.dispose()}catch(a){g.zb(a)}};
g.f.subscribe=function(a,b,c){a=g.x(a,b,c);this.D.push(a);return a};
g.f.clear=function(){g.Hb(this.D);this.D=[]};var Qb=g.p("yt.modules.registry_")||{};g.m("yt.modules.registry_",Qb,void 0);g.Eba=RegExp("[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]");g.Fba=RegExp("^[^\u0591-\u06ef\u06fa-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]*[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]");g.uh=RegExp("^[^A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]*[\u0591-\u06ef\u06fa-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]");g.Vb.prototype.Tf=!0;g.Ub={};g.Vb.prototype.Qe=function(){return this.A};
g.Gba=g.Wb("");g.Yb.prototype.Tf=!0;g.Yb.prototype.Qe=function(){return this.A};
g.Yb.prototype.xm=!0;g.Yb.prototype.Oe=g.ca(3);var oaa=/^(?:(?:https?|mailto|ftp):|[^&:/?#]*(?:[/?#]|$))/i,Xb={};g.ac("about:blank");g.dc.prototype.xm=!0;g.dc.prototype.Oe=g.ca(2);g.dc.prototype.Tf=!0;g.dc.prototype.Qe=function(){return this.A};
g.cc={};g.Hba=g.ec("<!DOCTYPE html>",0);g.vh=g.ec("",0);g.wh=g.ec("<br>",0);var hc={};var paa=/\.vflset|-vfl[a-zA-Z0-9_+=-]+/,qaa=/-[a-zA-Z]{2,3}_[a-zA-Z]{2,3}(?=(\/|$))/;g.Iba=Math.sign||function(a){return 0<a?1:0>a?-1:a};g.f=g.lc.prototype;g.f.clone=function(){return new g.lc(this.x,this.y)};
g.f.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};
g.f.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};
g.f.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};
g.f.scale=function(a,b){var c=g.ma(b)?b:a;this.x*=a;this.y*=c;return this};g.f=g.mc.prototype;g.f.clone=function(){return new g.mc(this.width,this.height)};
g.f.og=function(){return this.width*this.height};
g.f.aspectRatio=function(){return this.width/this.height};
g.f.isEmpty=function(){return!this.og()};
g.f.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.f.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
g.f.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
g.f.scale=function(a,b){var c=g.ma(b)?b:a;this.width*=a;this.height*=c;return this};var Dh,Eh,pc,Ih;g.xh=g.Ya("Opera");g.D=g.Za();g.yh=g.Ya("Edge");g.zh=g.yh||g.D;g.Ah=g.Ya("Gecko")&&!(g.ya(g.Xa.toLowerCase(),"webkit")&&!g.Ya("Edge"))&&!(g.Ya("Trident")||g.Ya("MSIE"))&&!g.Ya("Edge");g.Cc=g.ya(g.Xa.toLowerCase(),"webkit")&&!g.Ya("Edge");g.Cc&&g.Ya("Mobile");g.Bh=g.Ya("Macintosh");g.Ch=g.Ya("Windows");g.Jba=g.Ya("Linux")||g.Ya("CrOS");Dh=g.ea.navigator||null;Dh&&g.ya(Dh.appVersion||"","X11");g.Kba=g.Ya("Android");g.eh=g.nc();g.fh=g.Ya("iPad");g.Lba=g.Ya("iPod");
a:{var Fh="",Gh=function(){var a=g.Xa;if(g.Ah)return/rv\:([^\);]+)(\)|;)/.exec(a);if(g.yh)return/Edge\/([\d\.]+)/.exec(a);if(g.D)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(g.Cc)return/WebKit\/(\S+)/.exec(a);if(g.xh)return/(?:Version)[ \/]?(\S+)/.exec(a)}();
Gh&&(Fh=Gh?Gh[1]:"");if(g.D){var Hh=oc();if(null!=Hh&&Hh>(0,window.parseFloat)(Fh)){Eh=String(Hh);break a}}Eh=Fh}g.qc=Eh;pc={};Ih=g.ea.document;g.sc=Ih&&g.D?oc()||("CSS1Compat"==Ih.compatMode?(0,window.parseInt)(g.qc,10):5):void 0;var raa;raa=!g.D||g.tc(9);g.Mba=!g.Ah&&!g.D||g.D&&g.tc(9)||g.Ah&&g.rc("1.9.1");g.Jh=g.D&&!g.rc("9");g.Nba=g.D||g.xh||g.Cc;g.Oba=g.D&&!g.tc(9);var vc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};var vaa=g.Cc?"webkit":g.Ah?"moz":g.D?"ms":g.xh?"o":"",Lc=g.p("yt.dom.getNextId_");if(!Lc){Lc=function(){return++Pba};
g.m("yt.dom.getNextId_",Lc,void 0);var Pba=0};g.Qc.prototype.Sb=function(a){var b=[];Sc(this,a,b);return b.join("")};
var Uc={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},waa=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;Zc.prototype.reset=function(){this.context=this.C=this.B=this.A=null;this.D=!1};
var $c=new bb(function(){return new Zc},function(a){a.reset()},100);
g.Yc.prototype.then=function(a,b,c){return dd(this,g.na(a)?a:null,g.na(b)?b:null,c)};
g.Vc(g.Yc);g.Yc.prototype.cancel=function(a){0==this.A&&jb(function(){var b=new g.kd(a);fd(this,b)},this)};
g.Yc.prototype.R=function(a){this.A=0;g.Xc(this,2,a)};
g.Yc.prototype.Y=function(a){this.A=0;g.Xc(this,3,a)};
g.Yc.prototype.G=function(){for(var a;a=gd(this);)hd(this,a,this.A,this.K);this.H=!1};
var md=ab;g.t(g.kd,g.ta);g.kd.prototype.name="cancel";var pd=null;qd.prototype.D=function(){var a=g.p("gapi.config.update");a("googleapis.config/auth/useFirstPartyAuth",!0);var b=this.A.apiaryHost;g.va(g.za(b))||a("googleapis.config/root",(-1==b.indexOf("://")?"//":"")+b);b=this.A.sp;g.va(g.za(b))||a("googleapis.config/root-1p",(-1==b.indexOf("://")?"//":"")+b);a("googleapis.config/sessionIndex",g.v("SESSION_INDEX"));g.p("gapi.client.setApiKey")(this.A.innertubeApiKey)};
qd.prototype.C=function(){return{context:g.od(this.A)}};
qd.prototype.B=function(a,b,c){var d,e=!1;0<c.timeout&&(d=g.vb(function(){e||(e=!0,c.Cc&&c.Cc())},c.timeout));
Baa(this,a,b,function(a){if(!e)if(e=!0,d&&g.xb(d),a)c.W&&c.W(a);else if(c.onError)c.onError()})};var Caa,td;Caa={log_event:"events",log_interaction:"interactions"};g.yd={};td={};g.xd=0;g.sd=g.p("yt.logging.transport.logsQueue_")||{};g.m("yt.logging.transport.logsQueue_",g.sd,void 0);g.Kh="StopIteration"in g.ea?g.ea.StopIteration:{message:"StopIteration",stack:""};g.Ed=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;g.uf=g.Ya("Firefox");g.Lh=g.nc()||g.Ya("iPod");g.Mh=g.Ya("iPad");g.dh=g.Ya("Android")&&!(g.$a()||g.Ya("Firefox")||g.Ya("Opera")||g.Ya("Silk"));g.ch=g.$a();g.Nh=g.Ya("Safari")&&!(g.$a()||g.Ya("Coast")||g.Ya("Opera")||g.Ya("Edge")||g.Ya("Silk")||g.Ya("Android"))&&!(g.nc()||g.Ya("iPad")||g.Ya("iPod"));var Qd={},Eaa=0;g.Rd.prototype.Sb=function(){return{version:this.version,args:this.args}};
g.Sd.prototype.toString=function(){return this.topic};var Qba=g.p("yt.pubsub2.instance_")||new g.qb;g.qb.prototype.subscribe=g.qb.prototype.subscribe;g.qb.prototype.unsubscribeByKey=g.qb.prototype.sd;g.qb.prototype.publish=g.qb.prototype.Fa;g.qb.prototype.clear=g.qb.prototype.clear;g.m("yt.pubsub2.instance_",Qba,void 0);g.Oh=g.p("yt.pubsub2.subscribedKeys_")||{};g.m("yt.pubsub2.subscribedKeys_",g.Oh,void 0);g.Ph=g.p("yt.pubsub2.topicToKeys_")||{};g.m("yt.pubsub2.topicToKeys_",g.Ph,void 0);g.Qh=g.p("yt.pubsub2.isAsync_")||{};
g.m("yt.pubsub2.isAsync_",g.Qh,void 0);g.m("yt.pubsub2.skipSubKey_",null,void 0);var Ee=(0,g.E)().toString();var ee=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance||{};g.t(Vd,g.Rd);var Qaa=new g.Sd("timing-sent",Vd);g.f=g.Wd.prototype;g.f.getHeight=function(){return this.bottom-this.top};
g.f.clone=function(){return new g.Wd(this.top,this.right,this.bottom,this.left)};
g.f.contains=function(a){return g.Xd(this,a)};
g.f.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};
g.f.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};
g.f.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
g.f.scale=function(a,b){var c=g.ma(b)?b:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};g.f=g.Yd.prototype;g.f.clone=function(){return new g.Yd(this.left,this.top,this.width,this.height)};
g.f.contains=function(a){return a instanceof g.lc?a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height:this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height};
g.f.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.f.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
g.f.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
g.f.scale=function(a,b){var c=g.ma(b)?b:a;this.left*=a;this.width*=a;this.top*=c;this.height*=c;return this};ce.prototype.toString=function(){return this.region.toString()+": "+this.timing+" => "+this.url};
de.prototype.toString=function(){return["progress",this.progress,"timing",this.timing,"area",this.og].join(": ")};
be.C=.1;be.A=/url\(["']?(http[^'"\)]+)['"]?\)/i;be.B="mark_iframe_loaded: ";be.D=20;var Oaa={vc:!0},Haa=/^mark_/i,we={'script[name="scheduler/scheduler"]':"sj",'script[name="player/base"]':"pj",'link[rel="stylesheet"][name="www-player"]':"pc",'script[name="desktop_polymer/desktop_polymer"]':"dpj",'link[rel="import"][name="desktop_polymer"]':"dph",'script[name="mobile_polymer/mobile_polymer"]':"mpj",'link[rel="import"][name="mobile_polymer"]':"mph",'script[name="player-plasma-phone/base"]':"mpppj",'script[name="player-plasma-tablet/base"]':"mpptj",'link[rel="stylesheet"][name="mobile-polymer-player"]':"mppc"},
qe={ad_at:"adType",cpn:"clientPlaybackNonce",csn:"clientScreenNonce",yt_lt:"loadType",yt_ad:"isMonetized",yt_ad_pr:"prerollAllowed",yt_red:"isRedSubscriber",yt_vis:"isVisible"},Jaa=["isMonetized","prerollAllowed","isRedSubscriber","isVisible"],Kaa=(0,g.q)(ee.clearResourceTimings||ee.webkitClearResourceTimings||ee.mozClearResourceTimings||ee.msClearResourceTimings||ee.oClearResourceTimings||g.fa,ee);g.He.prototype.preventDefault=function(){this.event&&(this.event.returnValue=!1,this.event.preventDefault&&this.event.preventDefault())};
g.He.prototype.stopPropagation=function(){this.event&&(this.event.cancelBubble=!0,this.event.stopPropagation&&this.event.stopPropagation())};
g.He.prototype.stopImmediatePropagation=function(){this.event&&(this.event.cancelBubble=!0,this.event.stopImmediatePropagation&&this.event.stopImmediatePropagation())};
var Raa={stopImmediatePropagation:1,stopPropagation:1,preventMouseEvent:1,preventManipulation:1,preventDefault:1,layerX:1,layerY:1,scale:1,rotation:1,webkitMovementX:1,webkitMovementY:1};g.Ie=g.p("yt.events.listeners_")||{};g.m("yt.events.listeners_",g.Ie,void 0);var Ke=g.p("yt.events.counter_")||{count:0};g.m("yt.events.counter_",Ke,void 0);var Saa={enablejsapi:1},Taa={},Uaa={allowscriptaccess:"always",allowfullscreen:"true",bgcolor:"#000000"};Pe.prototype.clone=function(){var a=new Pe,b;for(b in this)if(this.hasOwnProperty(b)){var c=this[b];"object"==g.ha(c)?a[b]=g.Ua(c):a[b]=c}return a};g.Re=null;g.We=/\s*;\s*/;g.f=g.Ve.prototype;g.f.isEnabled=function(){return window.navigator.cookieEnabled};
g.f.set=function(a,b,c,d,e,h){if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');g.da(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";h=h?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,g.E)()+1E3*c)).toUTCString();this.A.cookie=a+"="+b+e+d+c+h};
g.f.get=function(a,b){for(var c=a+"=",d=(this.A.cookie||"").split(g.We),e=0,h;h=d[e];e++){if(0==h.lastIndexOf(c,0))return h.substr(c.length);if(h==a)return""}return b};
g.f.remove=function(a,b,c){var d=g.da(this.get(a));this.set(a,"",0,b,c);return d};
g.f.Kb=g.ca(4);g.f.lb=g.ca(5);g.f.isEmpty=function(){return!this.A.cookie};
g.f.ob=g.ca(0);g.f.oe=g.ca(6);g.f.clear=function(){for(var a=g.Xe(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};
g.Ye=new g.Ve("undefined"==typeof window.document?null:window.document);g.Ye.C=3950;g.Rh=g.D?"focusin":"DOMFocusIn";g.Sh=g.D?"focusout":"DOMFocusOut";g.Th=g.Cc?"webkitTransitionEnd":g.xh?"otransitionend":"transitionend";g.Uh=g.Ah?"MozUserSelect":g.Cc||g.yh?"WebkitUserSelect":null;g.ga(g.kf);g.kf.prototype.getVersion=function(){return[this.major,this.minor,this.A]};var Vaa=/cssbin\/(?:debug-)?([a-zA-Z0-9_-]+?)(?:-2x|-web|-rtl|-vfl|.css)/;var Df;var Vh=g.Xa,Vh=Vh.toLowerCase();if(g.ya(Vh,"android")){var Wh=Vh.match(/android\D*(\d\.\d)[^\;|\)]*[\;\)]/);if(Wh)Df=Number(Wh[1]);else{var Xh={cupcake:1.5,donut:1.6,eclair:2,froyo:2.2,gingerbread:2.3,honeycomb:3,"ice cream sandwich":4,jellybean:4.1},Yh=Vh.match("("+g.Pa(Xh).join("|")+")");Df=Yh?Xh[Yh[0]]:0}}else Df=void 0;var Yaa=['video/mp4; codecs="avc1.42001E, mp4a.40.2"','video/webm; codecs="vp8.0, vorbis"'],Zaa=['audio/mp4; codecs="mp4a.40.2"'];g.t(qf,g.mb);qf.prototype.Va=function(a){for(var b=0;b<this.A.length;b++)if(this.A[b]==a){this.A.splice(b,1);a.target.removeEventListener(a.name,a.Nb);break}};
qf.prototype.U=function(){sf(this);qf.L.U.call(this)};var Waa={"api.invalidparam":2,auth:150,"drm.auth":150,heartbeat:150,"html5.unsupportedads":5,"fmt.noneavailable":5,"fmt.decode":5,"fmt.unplayable":5,"html5.missingapi":5,"html5.unsupportedlive":5,"drm.unavailable":5};g.t(vf,g.mb);var Xaa=["drm.unavailable","fmt.noneavailable","html5.missingapi","html5.unsupportedads","html5.unsupportedlive"];g.f=vf.prototype;g.f.getId=function(){return this.ha};
g.f.Co=function(a,b){this.isDisposed()||(xf(this,a),Bf(this,b),this.H&&yf(this))};
g.f.ez=function(){return this.hb};
g.f.UO=function(){if(!this.aa){var a=Ef(this);a&&"html5"==Gf(this)?(this.G="html5",this.H||this.Sg()):(Hf(this),this.G="html5",a&&this.M?(this.D.appendChild(this.M),this.Sg()):(this.A.loaded=!0,this.P=(0,g.q)(function(){var a=this.D,c=this.A.clone();g.p("yt.player.Application.create")(a,c);this.Sg()},this),this.aa=!0,a?this.P():(g.jc(this.A.assets.js,this.P),g.pf(this.A.assets.css))))}};
g.f.TO=function(){var a=this.A.clone();if(!this.F){var b=Af(this);b&&(this.F=window.document.createElement("span"),this.F.tabIndex=0,rf(this.ea,this.F,"focus",this.It),this.R=window.document.createElement("span"),this.R.tabIndex=0,rf(this.ea,this.R,"focus",this.It),g.Hc(this.F,b),g.Ic(this.R,b))}a.attrs.width=a.attrs.width||"100%";a.attrs.height=a.attrs.height||"100%";"flash"==Gf(this)?(this.G="flash",this.H||this.Sg()):(Hf(this),this.G="flash",this.A.loaded=!0,b=g.kf.getInstance(),b=g.mf(b)||!g.nf(b)?
a.url:a.urlV9As2,window!=window.top&&window.document.referrer&&(a.args.framer=window.document.referrer.substring(0,128)),g.of(this.D,b,a),this.Sg())};
g.f.It=function(){Af(this).focus()};
g.f.Sg=function(){if(!this.isDisposed()){var a=Af(this),b=!1;try{a&&a.getApiInterface&&a.getApiInterface()&&(b=!0)}catch(h){}if(b)if(this.aa=!1,a.isNotServable&&a.isNotServable(this.A.args.video_id))Cf(this);else{tf(this);this.H=!0;a=Af(this);a.addEventListener&&(this.T=Ff(this,a,"addEventListener"));a.removeEventListener&&(this.la=Ff(this,a,"removeEventListener"));for(var b=a.getApiInterface(),b=b.concat(a.getInternalApiInterface()),c=0;c<b.length;c++){var d=b[c];this.api[d]||(this.api[d]=Ff(this,
a,d))}for(var e in this.B)this.T(e,this.B[e]);yf(this);this.Ua&&this.Ua(this.api);this.X.Fa("onReady",this.api)}else this.Bb=g.vb((0,g.q)(this.Sg,this),50)}};
g.f.gP=function(){return this.H};
g.f.ie=function(a,b){if(!this.isDisposed()){var c=wf(this,b);if(c){if(!g.Ia(this.Hb,a)&&!this.B[a]){var d=$aa(this,a);this.T&&this.T(a,d)}this.X.subscribe(a,c);"onReady"==a&&this.H&&g.vb(g.r(c,this.api),0)}}};
g.f.aN=function(a,b){if(!this.isDisposed()){var c=wf(this,b);c&&this.X.unsubscribe(a,c)}};
g.f.hy=function(a){a=a?uaa:taa;for(var b=a(window.document.activeElement);b&&(1!=b.nodeType||b==this.F||b==this.R||(b.focus(),b!=window.document.activeElement));)b=a(b)};
g.f.hp=function(a){g.z("a11y-announce",a)};
g.f.NI=function(a){Cf(this,a)};
g.f.RI=function(a){g.z("WATCH_LATER_VIDEO_ADDED",a)};
g.f.SI=function(a){g.z("WATCH_LATER_VIDEO_REMOVED",a)};
g.f.vI=function(){this.bb||(g.ch?(this.ab=g.Bc(window.document),rf(this.Y,window,"scroll",this.hL),rf(this.Y,this.D,"touchmove",this.HK)):(rf(this.Y,this.D,"mousewheel",this.Xt),rf(this.Y,this.D,"wheel",this.Xt)),this.bb=!0)};
g.f.wI=function(){sf(this.Y);this.bb=!1};
g.f.Xt=function(a){g.Le(a)};
g.f.hL=function(){window.scrollTo(this.ab.x,this.ab.y)};
g.f.HK=function(a){a.preventDefault()};
g.f.Yz=function(){return this.G||Gf(this)};
g.f.Iz=function(){return this.kb};
g.f.cancel=function(){if(this.P){var a=this.P,b=g.ic(this.A.assets.js);window.spf.script.ignore(b,a)}g.xb(this.Bb);this.aa=!1};
g.f.U=function(){Hf(this);if(this.M&&this.A)try{this.M.destroy()}catch(b){g.zb(b)}this.Xa=null;for(var a in this.B)g.ea[this.B[a]]=null;this.hb=this.A=this.api=null;delete this.D;delete this.K;vf.L.U.call(this)};g.Jf={};g.If="player_uid_"+(1E9*Math.random()>>>0);var Rba=g.p("yt.abuse.botguardInitialized")||Se;g.m("yt.abuse.botguardInitialized",Rba,void 0);var Sba=g.p("yt.abuse.invokeBotguard")||g.Te;g.m("yt.abuse.invokeBotguard",Sba,void 0);var Tba=g.p("yt.abuse.dclkstatus.checkDclkStatus")||Ue;g.m("yt.abuse.dclkstatus.checkDclkStatus",Tba,void 0);var Uba=g.p("yt.player.exports.navigate")||g.ef;g.m("yt.player.exports.navigate",Uba,void 0);var Vba=g.p("yt.player.embed")||g.Kf;g.m("yt.player.embed",Vba,void 0);var Wba=g.p("yt.player.getPlayerByElement")||g.Lf;
g.m("yt.player.getPlayerByElement",Wba,void 0);var Xba=g.p("yt.util.activity.init")||g.Ne;g.m("yt.util.activity.init",Xba,void 0);var Yba=g.p("yt.util.activity.getTimeSinceActive")||g.Oe;g.m("yt.util.activity.getTimeSinceActive",Yba,void 0);var Zba=g.p("yt.util.activity.setTimestamp")||Me;g.m("yt.util.activity.setTimestamp",Zba,void 0);var Of,Tf;g.Sf=null;Tf="";g.Uf.prototype.stopPropagation=function(){this.$f=!0};
g.Uf.prototype.preventDefault=function(){this.defaultPrevented=!0;this.kv=!1};var kg,aca;g.$ba=!g.D||g.tc(9);kg=!g.D||g.tc(9);aca=g.D&&!g.rc("9");!g.Cc||g.rc("528");g.Ah&&g.rc("1.9b")||g.D&&g.rc("8")||g.xh&&g.rc("9.5")||g.Cc&&g.rc("528");g.Ah&&!g.rc("8")||g.D&&g.rc("9");g.t(g.Vf,g.Uf);
g.Vf.prototype.init=function(a,b){var c=this.type=a.type,d=a.changedTouches?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.currentTarget=b;var e=a.relatedTarget;e?g.Ah&&(g.sa(e,"nodeName")||(e=null)):"mouseover"==c?e=a.fromElement:"mouseout"==c&&(e=a.toElement);this.relatedTarget=e;null===d?(this.offsetX=g.Cc||void 0!==a.offsetX?a.offsetX:a.layerX,this.offsetY=g.Cc||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?
a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0):(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.rn=g.Bh?a.metaKey:a.ctrlKey;this.state=a.state;this.sb=a;a.defaultPrevented&&this.preventDefault()};
g.Vf.prototype.stopPropagation=function(){g.Vf.L.stopPropagation.call(this);this.sb.stopPropagation?this.sb.stopPropagation():this.sb.cancelBubble=!0};
g.Vf.prototype.preventDefault=function(){g.Vf.L.preventDefault.call(this);var a=this.sb;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,aca)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
g.Vf.prototype.Hq=g.ca(7);var Wf="closure_listenable_"+(1E6*Math.random()|0),cba=0;Zf.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.A))return!1;var e=this.A[a];b=$f(e,b,c,d);return-1<b?(Yf(e[b]),g.Ja(e,b),0==e.length&&(delete this.A[a],this.C--),!0):!1};
Zf.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.A)if(!a||c==a){for(var d=this.A[c],e=0;e<d.length;e++)++b,Yf(d[e]);delete this.A[c];this.C--}return b};var hg="closure_lm_"+(1E6*Math.random()|0),ng={},jg=0,qg="__closure_events_fn_"+(1E9*Math.random()>>>0);g.t(g.rg,g.mb);g.rg.prototype[Wf]=!0;g.f=g.rg.prototype;g.f.kj=function(){return this.vo};
g.f.si=g.ca(8);g.f.addEventListener=function(a,b,c,d){g.dg(this,a,b,c,d)};
g.f.removeEventListener=function(a,b,c,d){g.lg(this,a,b,c,d)};
g.f.dispatchEvent=function(a){var b,c=this.kj();if(c){b=[];for(var d=1;c;c=c.kj())b.push(c),++d}c=this.qx;d=a.type||a;if(g.ka(a))a=new g.Uf(a,c);else if(a instanceof g.Uf)a.target=a.target||c;else{var e=a;a=new g.Uf(d,c);g.Wa(a,e)}var e=!0,h;if(b)for(var k=b.length-1;!a.$f&&0<=k;k--)h=a.currentTarget=b[k],e=sg(h,d,!0,a)&&e;a.$f||(h=a.currentTarget=c,e=sg(h,d,!0,a)&&e,a.$f||(e=sg(h,d,!1,a)&&e));if(b)for(k=0;!a.$f&&k<b.length;k++)h=a.currentTarget=b[k],e=sg(h,d,!1,a)&&e;return e};
g.f.U=function(){g.rg.L.U.call(this);this.removeAllListeners();this.vo=null};
g.f.O=function(a,b,c,d){return g.ag(this.Y,String(a),b,!1,c,d)};
g.f.Va=function(a,b,c,d){return this.Y.remove(String(a),b,c,d)};
g.f.removeAllListeners=function(a){return this.Y?this.Y.removeAll(a):0};g.t(g.vg,g.mb);g.f=g.vg.prototype;g.f.rb=0;g.f.U=function(){g.vg.L.U.call(this);this.stop();delete this.A;delete this.C};
g.f.start=function(a){this.stop();this.rb=g.tg(this.Hc,g.da(a)?a:this.B)};
g.f.stop=function(){this.isActive()&&g.ug(this.rb);this.rb=0};
g.f.isActive=function(){return 0!=this.rb};
g.f.Sl=function(){this.rb=0;this.A&&this.A.call(this.C)};var Bg=[],Cg=0,Dg=0,zg=[],wg=0,Ag={},xg=new g.vg(mba,1E3);var Eg=null,Hg=[];var Lg,bh,ah,Ng,Mg,xba,qba,tba,rba,sba,Xg;Ng=0;Mg=0;xba=["server_prefetched_vast","vmap"];qba=[900,60,"waiting"];tba=[500,99,"waiting"];rba=[300,60,"waiting"];sba=[400,99,"waiting"];Xg=[300,101,"done"];window.yt=window.yt||{};g.m("yt.setConfig",g.tb,void 0);g.m("yt.pushConfigArray",function(a,b){var c=g.v(a,void 0);c?c.push(b):g.tb(a,[b])},void 0);
g.m("yt.getConfig",g.v,void 0);g.m("yt.hasMsg",g.Bb,void 0);g.m("yt.pubsub.publish",g.z,void 0);g.m("yt.pubsub.subscribe",g.x,void 0);g.m("yt.setMsg",function(a){rb(g.Ab,arguments)},void 0);
g.m("yt.setGoogMsg",function(a){rb(g.Ab,arguments)},void 0);
g.m("ytcsi.tick",g.me,void 0);g.t(hh,g.Ob);
hh.prototype.enable=function(){window.onload=oba;window.onunload=pba;window.onerror=naa;var a=window.ytspf||{};a.enabled?(window.addEventListener&&(window.addEventListener("spfclick",Jg),window.addEventListener("spfhistory",Kg),window.addEventListener("spfrequest",Pg),window.addEventListener("spfpartprocess",Tg),window.addEventListener("spfpartdone",Ug),window.addEventListener("spfprocess",Vg),window.addEventListener("spfdone",Yg),window.addEventListener("spferror",Zg),window.addEventListener("spfreload",
$g),window.addEventListener("spfjsbeforeunload",ih)),a.config=a.config||{},window.ytdepmap?window.spf.script.ready("spf",function(){a.enabled=window.spf.init(a.config)}):a.enabled=window.spf.init(a.config),this.subscribe("init",vba),this.subscribe("dispose",wba)):window.spf.dispose();
this.subscribe("init",this.init,this);this.subscribe("dispose",this.dispose,this)};
hh.prototype.init=function(){hh.L.init.call(this);(window.ytspf||{}).enabled||window.spf.dispose();var a=window.ytPageFrameLoaded||!1,b,c;!a&&g.v("PAGEFRAME_JS")?(b=g.v("PAGEFRAME_JS",void 0),c=function(){window.ytPageFrameLoaded=!0;g.p("ytbin.www.pageframe.setup")()}):a&&(a=g.p("yt.www.masthead.loadSearchbox"))&&a();
var a=g.v("JS_COMMON_MODULE"),d=g.v("JS_PAGE_MODULES");d||(d=[a]);a=g.v("JS_DELAY_LOAD",0);0<a?(g.xb(this.B),this.B=g.vb(function(){b&&g.jc(b,c);window.spf.script.require(d)},a)):(b&&g.jc(b,c),window.spf.script.require(d));
bba();Naa();Iaa();Ce(!0);g.le(!1);g.v("SERVICE_WORKER_KILLSWITCH",void 0)||"serviceWorker"in window.navigator&&"https:"==window.location.protocol&&(g.Pc("service_worker_enabled")?zba():window.navigator.serviceWorker.controller&&window.navigator.serviceWorker.getRegistration().then(Aba))};
hh.prototype.dispose=function(){g.xb(this.B);var a=g.p("ytbin.www.pageframe.cancelSetup");a&&a();g.yb(Of);if(a=g.Qf())a.removeEventListener("onReady",Pf),a.removeEventListener("onStateChange",Pf);Ce(!1);hh.L.dispose.call(this)};
hh.prototype.disable=function(){hh.L.disable.call(this);window.removeEventListener&&(window.removeEventListener("spfclick",Jg),window.removeEventListener("spfhistory",Kg),window.removeEventListener("spfrequest",Pg),window.removeEventListener("spfpartprocess",Tg),window.removeEventListener("spfpartdone",Ug),window.removeEventListener("spfprocess",Vg),window.removeEventListener("spfdone",Yg),window.removeEventListener("spferror",Zg),window.removeEventListener("spfreload",$g),window.removeEventListener("spfjsbeforeunload",
ih));window.onload=null;window.onunload=null;window.onerror=null};
g.Tb(new hh);})(_yt_www);
